#!/usr/bin/env python3
"""Pack TYGenICamReg CSV files into regaddr_csv_data.h for regaddr_convert.cpp.

Run this after changing any register CSV:
    python3 tools/gen_regaddr_csv_data.py
"""

import argparse
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
DEFAULT_CSV_DIR = os.path.join(PROJECT_DIR, '..', '..', '..', '..', 'TYGenICamReg', 'csv')
DEFAULT_OUTPUT = os.path.join(PROJECT_DIR, 'src', 'regaddr_csv_data.h')

# Must stay in sync with the file list in regaddr_convert.cpp.
CSV_FILES = [
    'GigE/BootstrapReg.csv',
    'gmsl/BootstrapReg.csv',
    'usb3vison/BootstrapReg.csv',
    'BaseReg.csv',
    'Device.csv',
    'Stream.csv',
    'LightSource.csv',
    'Additional.csv',
    'Event.csv',
]

DELIMITER = 'CSVDATA'


def symbol_name(relative_path):
    stem = relative_path.replace('/', '_').replace('.', '_')
    return 'k' + ''.join(part[:1].upper() + part[1:] for part in stem.split('_'))


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--csv-dir', default=DEFAULT_CSV_DIR)
    parser.add_argument('--output', default=DEFAULT_OUTPUT)
    parser.add_argument('--check', action='store_true',
                        help='exit non-zero if the output file is out of date')
    args = parser.parse_args()

    chunks = [
        '// Generated by tools/gen_regaddr_csv_data.py. Do not edit by hand.\n',
        '// Regenerate after changing any TYGenICamReg/csv/*.csv file.\n',
        '\n',
        '#ifndef REGADDR_CSV_DATA_H\n',
        '#define REGADDR_CSV_DATA_H\n',
        '\n',
        '#include <string_view>\n',
        '\n',
        'namespace regaddr_csv_data {\n',
    ]

    entries = []
    for relative_path in CSV_FILES:
        path = os.path.join(args.csv_dir, relative_path)
        with open(path, encoding='utf-8') as handle:
            content = handle.read()
        if f'){DELIMITER}"' in content:
            raise SystemExit(f'{relative_path}: content conflicts with raw string delimiter')
        name = symbol_name(relative_path)
        entries.append((relative_path, name))
        chunks.append(f'\ninline constexpr std::string_view {name} = R"{DELIMITER}(\n')
        chunks.append(content)
        chunks.append(f'){DELIMITER}";\n')

    chunks.append('\nstruct CsvFile {\n')
    chunks.append('    std::string_view path;\n')
    chunks.append('    std::string_view content;\n')
    chunks.append('};\n')
    chunks.append(f'\ninline constexpr CsvFile kFiles[{len(entries)}] = {{\n')
    for relative_path, name in entries:
        chunks.append(f'    {{"{relative_path}", {name}}},\n')
    chunks.append('};\n')
    chunks.append('\n} // namespace regaddr_csv_data\n')
    chunks.append('\n#endif // REGADDR_CSV_DATA_H\n')

    text = ''.join(chunks)

    if args.check:
        try:
            with open(args.output, encoding='utf-8') as handle:
                current = handle.read()
        except FileNotFoundError:
            current = None
        if current != text:
            print(f'{args.output} is out of date; run tools/gen_regaddr_csv_data.py',
                  file=sys.stderr)
            return 1
        return 0

    with open(args.output, 'w', encoding='utf-8') as handle:
        handle.write(text)
    print(f'wrote {args.output} ({len(entries)} CSV files, {len(text)} bytes)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
