// Generated by tools/gen_regaddr_csv_data.py. Do not edit by hand.
// Regenerate after changing any TYGenICamReg/csv/*.csv file.

#ifndef REGADDR_CSV_DATA_H
#define REGADDR_CSV_DATA_H

#include <string_view>

namespace regaddr_csv_data {

inline constexpr std::string_view kGigEBootstrapRegCsv = R"CSVDATA(
DeviceTLVersion_RegAddr,integer,4,0x0

DeviceType_RegAddr,integer,4,0x4

GevMACAddrHigh_RegAddr,integer,4,0x8

GevMACAddrLow_RegAddr,integer,4,0xc

SupportedIPConfiguration_RegAddr,integer,4,0x10
CurrentIPConfiguration_RegAddr,integer,4,0x14

GevCurrentIPAddressVal_RegAddr,integer,4,0x24
GevCurrentSubnetMaskVal_RegAddr,integer,4,0x34
GevCurrentDefaultGatewayVal_RegAddr,integer,4,0x44

DeviceManufacturerName_RegAddr,string,32,0x48

DeviceModelName_RegAddr,string,32,0x68

DeviceVersion_RegAddr,string,32,0x88

DeviceManufacturerInfo_RegAddr,string,48,0xa8

DeviceSerialNumber_RegAddr,string,16,0xd8

DeviceUserID_RegAddr,string,32,0xe8

GevFirstURL_RegAddr,string,512,0x200

GevSecondURL_RegAddr,string,512,0x400

GevNumberOfInterfaces_RegAddr,integer,4,0x600

GevPersistentIPAddressVal_RegAddr,integer,4,0x64c

GevPersistentSubnetMaskVal_RegAddr,integer,4,0x65c

GevPersistentDefaultGatewayVal_RegAddr,integer,4,0x66c

GevLinkSpeedVal_RegAddr,integer,4,0x670

GevStreamChannelCount_RegAddr,integer,4,0x904

GevSupportedInquiry_RegAddr,integer,4,0x934

GevHeartbeatTimeoutVal_RegAddr,integer,4,0x938

GVCPConfiguraton_RegAddr,integer,4,0x954

GevGVCPPendingTimeout_RegAddr,integer,4,0x958

//(CCP)M R/W 4 Control Channel Privilege register.
GevCCP_RegAddr,integer,4,0xa00

//(MCP)M R/W 4 Message Channel Port register.
GevMCP_RegAddr,integer,4,0xb00

//(MCDA)M R/W 4 Message Channel Destination Address register.
GevMCDA_RegAddr,integer,4,0xb10

//(MCTT) R/W 4 Message Channel Transmission Timeout register 
GevMCTT_RegAddr,integer,4,0xb14

//(MCRC) R/W 4 Message Channel Retry Count register 
GevMCRC_RegAddr,integer,4,0xb18

//(MCSP) R/W 4 Message Channel Source Port register 
GevMCSP_RegAddr,integer,4,0xb1c

//(SCP0) M1 R/W 4 First Stream Channel Port register.
GevStream_RegAddr,integer,4,0xd00

//(SCPS0)M1 R/W 4 First Stream Channel Packet Size register.
GevSCPSPacketSizeVal_RegAddr,integer,4,0xd04

//(SCPD0)M2 R/W 4 First Stream Channel Packet Delay register.
GevSCPDVal_RegAddr,integer,4,0xd08

//(SCDA0)M1 R/W 4 First Stream Channel Destination Address register.
GevSCDA_RegAddr,integer,4,0xd18

//(SCSP0)O R 4 First Stream Channel Source Port register.
GevSCSP_RegAddr,integer,4,0xd1c
)CSVDATA";

inline constexpr std::string_view kGmslBootstrapRegCsv = R"CSVDATA(
DeviceTLVersion_RegAddr,integer,4,0x0

DeviceType_RegAddr,integer,4,0x4

GevCurrentIPAddressVal_RegAddr,integer,4,0x24

GevCurrentSubnetMaskVal_RegAddr,integer,4,0x34

GevCurrentDefaultGatewayVal_RegAddr,integer,4,0x44

DeviceManufacturerName_RegAddr,string,32,0x48

DeviceModelName_RegAddr,string,32,0x68

DeviceVersion_RegAddr,string,32,0x88

DeviceManufacturerInfo_RegAddr,string,48,0xa8

DeviceSerialNumber_RegAddr,string,16,0xd8

DeviceUserID_RegAddr,string,32,0xe8

GevPersistentIPAddressVal_RegAddr,integer,4,0x64c

GevPersistentSubnetMaskVal_RegAddr,integer,4,0x65c

GevPersistentDefaultGatewayVal_RegAddr,integer,4,0x66c

GevFirstURL_RegAddr,string,512,0x200

GevSecondURL_RegAddr,string,512,0x400

GevStreamChannelCount_RegAddr,integer,4,0x904

GevSupportedInquiry_RegAddr,integer,4,0x934

GevHeartbeatTimeoutVal_RegAddr,integer,4,0x938

GVCPConfiguraton_RegAddr,integer,4,0x954

GevGVCPPendingTimeout_RegAddr,integer,4,0x958

//(CCP)M R/W 4 Control Channel Privilege register.
GevCCP_RegAddr,integer,4,0xa00

//(MCP)M R/W 4 Message Channel Port register.
GevMCP_RegAddr,integer,4,0xb00

//(MCDA)M R/W 4 Message Channel Destination Address register.
GevMCDA_RegAddr,integer,4,0xb10

//(MCTT) R/W 4 Message Channel Transmission Timeout register 
GevMCTT_RegAddr,integer,4,0xb14

//(MCRC) R/W 4 Message Channel Retry Count register 
GevMCRC_RegAddr,integer,4,0xb18

//(MCSP) R/W 4 Message Channel Source Port register 
GevMCSP_RegAddr,integer,4,0xb1c

//(SCP0) M1 R/W 4 First Stream Channel Port register.
GevStream_RegAddr,integer,4,0xd00

//(SCPS0)M1 R/W 4 First Stream Channel Packet Size register.
GevSCPSPacketSizeVal_RegAddr,integer,4,0xd04

//(SCPD0)M2 R/W 4 First Stream Channel Packet Delay register.
GevSCPDVal_RegAddr,integer,4,0xd08

//(SCDA0)M1 R/W 4 First Stream Channel Destination Address register.
GevSCDA_RegAddr,integer,4,0xd18

//(SCSP0)O R 4 First Stream Channel Source Port register.
GevSCSP_RegAddr,integer,4,0xd1c
)CSVDATA";

inline constexpr std::string_view kUsb3visonBootstrapRegCsv = R"CSVDATA(
DeviceGenCPVersion_RegAddr,integer,4,0x0

DeviceManufacturerName_RegAddr,string,64,0x4

DeviceModelName_RegAddr,string,64,0x44

DeviceFamilyName_RegAddr,string,64,0x84

DeviceVersion_RegAddr,string,64,0xc4

DeviceManufacturerInfo_RegAddr,string,64,0x104

DeviceSerialNumber_RegAddr,string,64,0x144

DeviceUserID_RegAddr,string,64,0x184

DeviceDeviceCapability_RegAddr,integer,8,0x1c4

DeviceMaximumDeviceResponseTime_RegAddr,integer,4,0x1cc

DeviceManifestTableAddress_RegAddr,integer,8,0x1d0

DeviceSBRMAddress_RegAddr,integer,8,0x1d8

DeviceDeviceConfiguration_RegAddr,integer,8,0x1e0

DeviceHeartbeatTimeout_RegAddr,integer,4,0x1e8

DeviceMessageChannelID_RegAddr,integer,4,0x1ec

DeviceTimestamp_RegAddr,integer,8,0x1f0

DeviceTimestampLatch_RegAddr,integer,4,0x1f8

DeviceTimestampIncrement_RegAddr,integer,8,0x1fc

DeviceAccessPrivilege_RegAddr,integer,4,0x204

DeviceProtocolEndianess_RegAddr,integer,4,0x208

DeviceImplementationEndianess_RegAddr,integer,4,0x20c

DeviceDeviceSoftwareVersion_RegAddr,string,64,0x210

DeviceU3VVersion_RegAddr,integer,4,0x10000

DeviceU3VCPCapability_RegAddr,integer,8,0x10004

DeviceU3VCPConfiguration_RegAddr,integer,8,0x1000c

DeviceMaximumCommandTransferLength_RegAddr,integer,4,0x10014

DeviceMaximumAcknowledgeTransferLength_RegAddr,integer,4,0x10018

DeviceNumberofStreamChannels_RegAddr,integer,4,0x1001c

DeviceSIRMAddress_RegAddr,integer,8,0x10020

DeviceSIRMLength_RegAddr,integer,4,0x10028

DeviceEIRMAddress_RegAddr,integer,8,0x1002c

DeviceEIRMLength_RegAddr,integer,4,0x10034

DeviceIIDC2Address_RegAddr,integer,8,0x10038

DeviceCurrentSpeed_RegAddr,integer,4,0x10040

DeviceSIInfo_RegAddr,integer,4,0x20000

DeviceSIControl_RegAddr,integer,4,0x20004

DeviceSIRequiredPayloadSize_RegAddr,integer,8,0x20008

DeviceSIRequiredLeaderSize_RegAddr,integer,4,0x20010

DeviceSIRequiredTrailerSize_RegAddr,integer,4,0x20014

DeviceSIMaximumLeaderSize_RegAddr,integer,4,0x20018

DeviceSIPayloadTransferSize_RegAddr,integer,4,0x2001c

DeviceSIPayloadTransferCount_RegAddr,integer,4,0x20020

DeviceSIPayloadFinalTransfer1Size_RegAddr,integer,4,0x20024

DeviceSIPayloadFinalTransfer2Size_RegAddr,integer,4,0x20028

DeviceSIMaximumTrailerSize_RegAddr,integer,4,0x2002c

DeviceSISupportedPayloadModes_RegAddr,integer,4,0x20030

DeviceSIPayloadMode_RegAddr,integer,4,0x20034

DeviceSIGSIRMAddress_RegAddr,integer,8,0x20038

DeviceSIGSIRMSize_RegAddr,integer,4,0x20040

DeviceEIControl_RegAddr,integer,4,0x21000

DeviceEIMaximumEventTransferLength_RegAddr,integer,4,0x21004

DeviceEIEventTestControl_RegAddr,integer,4,0x21008

TerminalBridge_RegAddr,byte array,4096,0x30000

ManifestTableAddress_RegAddr,byte array,65536,0x40000

XML_AddrBase_RegAddr,byte array,65536,0x50000

/////////////////////////////////////////////////////////////////////////////////////////
//----------Percipio custom bootstrap extended register base address--------------------//
//------------------------------BASE ADDR: 0x00800000 -----------------------------///////
//-----------------------------0x00800000 - 0x01000000-----------------------------///////
//////////////////////////////////////////////////////////////////////////////////////////
U3VSupportedInquiry_RegAddr,integer,4,0x800000

DeviceResourceRST_RegAddr,integer,4
DebugModeControl_RegAddr,integer,4
)CSVDATA";

inline constexpr std::string_view kBaseRegCsv = R"CSVDATA(
//----------Component function query-----------//
//-----False: Not supported------//
//-----True:Supported---------//
CategoryConfig_RegAddr,struct,4,0x10000000,,RO,Category Support Inq
DeviceCategorySupportInq_Bit,bit,0
DepthCategorySupportInq_Bit,bit
LeftCameraCategorySupportInq_Bit,bit
RightCameraCategorySupportInq_Bit,bit
IntensityCameraCategorySupportInq_Bit,bit
LaserCategorySupportInq_Bit,bit
StorageCategorySupportInq_Bit,bit
UserSetCategorySupportInq_Bit,bit

//The actual offset address corresponding to the current stream index, with multiple consecutive uint32_t values storing the offset addresses of different streams respectively.
//DepthCategory_RegAddr / ColorCameraCategory_RegAddr / LeftCameraCategory_RegAddr/ RightCameraCategory_RegAddr
CurrentSource_BaseRegAddr,integer,100,0x10000008

//This address is used to read the offset address of the Source register from the original camera
//Source:Range;Intensity;BinocularLeft;BinocularRight

%headercode
#define Range_BaseRegAddr                              (CurrentSource_BaseRegAddr + 0x00)
#define Intensity_BaseRegAddr                          (CurrentSource_BaseRegAddr + 0x04)
#define BinocularLeft_BaseRegAddr                      (CurrentSource_BaseRegAddr + 0x08)
#define BinocularRight_BaseRegAddr                     (CurrentSource_BaseRegAddr + 0x0c)
%enddef

//-------Category Offset Register<bit 27 - 24>-------//
//------------------Component offset address definition-----------------//
DeviceCategory_RegAddr,integer,4,0x01000000
DepthCategory_RegAddr,integer,4,0x02000000
LeftCameraCategory_RegAddr,integer,4,0x03000000
RightCameraCategory_RegAddr,integer,4,0x04000000
ColorCameraCategory_RegAddr,integer,4,0x05000000
LightSourceCategory_RegAddr,integer,4,0x07000000
StorageCategory_RegAddr,integer,4,0x09000000
UserSetCategory_RegAddr,integer,4,0x0a000000
FileAccessCtrlCategory_RegAddr,integer,4,0x0b000000
SequencerCtrlCategory_RegAddr,integer,4,0x0c000000

//--------Category Mask-------//
//------Component offset address mask------//
Category,mask,4,0x0f000000

//----------Address Mask---------//
//---Function/parameter register address mask----//
OffsetAddress,mask,4,0x00ffffff
)CSVDATA";

inline constexpr std::string_view kDeviceCsv = R"CSVDATA(
//--------------------------Device Register -----------------------------------//
//------------------------------BASE ADDR: 0x01000000 -------------------------//
//Block0 : 0x100000 - 0x400000
//Block1 : 0x400000 - 0x800000
//Block2 : 0x800000 - 0xFFFFFF
//----------------------------DeviceCategory Register <Block0>-----------------//
//-------------------------------0x100000 - 0x400000---------------------------//
AcquisitionStart_RegAddr,integer,4,0x100000
AcquisitionStop_RegAddr,integer,4

//----------Device component function/parameter register address 1---------//
//DeviceSerialNumber_Reg,string,512,0x0100
//DeviceVendorName_Reg,string,512
//DeviceModelName_Reg,string,512
//DeviceUserDefinedName_Reg,string,512
DeviceHardwareVersion_Reg,string,256
DeviceHardWareModel_Reg,string,256
DeviceFirmwareVersion_Reg,string,512
DeviceBuildHash_Reg,string,512
DeviceConfigVersion_Reg,string,512
DeviceTechModel_Reg,string,512
DeviceGeneratedTime_Reg,string,512
DeviceCalibrationTime_Reg,string,512

DeviceConnectionSpeedResv_RegAddr,byte array,800
//DeviceConnectionSpeed_RegAddr,integer,200
//Current IP Address
//GevCurrentIPAddressVal_Reg,integer,4
//Current Net Mask
//GevCurrentSubnetMaskVal_Reg,integer,4
//Current GateWay
//GevCurrentDefaultGatewayVal_Reg,integer,4

//NTP selected
DeviceNTPServerIP_RegAddr,integer,4

DeviceReset_RegAddr,integer,4

DeviceErrCode_RegAddr,integer,4

DeviceFrameRecvTimeOut_RegAddr,integer,4

//Resved addr
DeviceBlock0Resv_RegAddr,byte array,512

PostProcessingControl_RegAddr,integer,1024

DeviceFeaturePersistence_RegAddr,integer,4
DeviceRegistersStreaming_RegAddr,integer,4
DeviceRegistersCheck_RegAddr,integer,4
DeviceRegistersValid_RegAddr,integer,4

//PayloadSize ReadOnly
PayloadSize_RegAddr,integer,4

//----------------------------DeviceCategory Register <Block1>-----------------//
//-------------------------------0x400000 - 0x800000---------------------------//
//----------Device component function/parameter register address -------------//
DeviceFuncInq_RegAddr,struct,4,0x400000,DeviceCategory_RegAddr,RO,Device Func Inq
invalidator,UserSetLoad
invalidator,AcquisitionMode
//Trigger function
TriggerModeSupportInq_Bit,bit,0
//Trigger Mode Set On Support Inq
TriggerModeOnSupportInq_Bit
//Trigger Mode Set Off Support Inq
TriggerModeOffSupportInq_Bit
//Frame Rate Control
AcqFrameRatePresInq_Bit
//Trigger delay function
TriggerDelaySupportInq_Bit
//Triggers IO output level control function
TriggerOutIOCtrlSupportInq_Bit
//Triggers IO output level duration control function
TriggerOutDurationCtrlSupportInq_Bit
//cmos synchronous switch control function
CMOSSyncSupportInq_Bit
//Time synchronization status query function
TimeSyncAckSupportInq_Bit
//Capture time statistics function
CaptureTimeStatisticSupportInq_Bit
//IR undistortion function
IRUndistortionSupportInq_Bit
//Post process params storage
PostProcessParams_SupportInq_Bit
//SequencerControl function
SequencerConfig_SupportInq_Bit
//DigitalIOControl function
DigitalIOControl_SupportInq_Bit
//DeviceLogControl function
DeviceLogControl_SupportInq_Bit
//Post process control parameter
PostProcessingControl_SupportInq_Bit
//FirmWare update function
FirmwareUpdate_SupportInq_Bit
//Event control function
EventControl_SupportInq_Bit
//Registers Streaming function
RegistersStreaming_SupportInq_Bit
//Region control function
RegionControl_SupportInq_Bit
//Watermark control function
WatermarkControl_SupportInq_Bit
//Accel IMU data correction post process function
AccelFrameTransformed_SupportInq_Bit
//Gyro IMU data correction post process function
GyroFrameTransformed_SupportInq_Bit

DeviceStreamAsyncInq_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Device Stream Async Mode
StreamAsyncOffSupportInq_Bit,bit,0
StreamAsyncDepthSupportInq_Bit
StreamAsyncColorCameraSupportInq_Bit
StreamAsyncDepthColorCameraSupportInq_Bit
StreamAsyncAllSupportInq_Bit

//Time synchronization mode supports query
DeviceTimeSyncModeInq_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Device Time Sync Mode
TimeSyncNoneSupportInq_Bit,bit,0
TimeSyncHostSupportInq_Bit
TimeSyncNTPSupportInq_Bit
TimeSyncPTPSlaveSupportInq_Bit
TimeSyncCanSupportInq_Bit
TimeSyncPTPMasterSupportInq_Bit

//Trigger mode setting
//TriggerModeEx_RegAddr,byte array,132

AcquisitionModeInq_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Device Acquisition Mode Inq
//SingleFrame
AcqModeSingleFrameInq_Bit,bit,0
//MultiFrame
AcqModeMultiFrameInq_Bit
//Continuous
AcqModeContinuousInq_Bit

AcquisitionMode_RegAddr,integer,4

//acquisition frame rate setting
AcquisitionFrameRate_RegAddr,float,4

//acquisition frame rate min
AcquisitionFrameRateMin_RegAddr,float,4

//acquisition frame rate max
AcquisitionFrameRateMax_RegAddr,float,4

//acquisition frame rate enable
AcquisitionFrameRateEnable_RegAddr,integer,4


//Trigger delay time setting
TriggerDelayUs_RegAddr,integer,4

//Trigger delay time min
TriggerDelayUsMin_RegAddr,integer,4

//Trigger delay time max
TriggerDelayUsMax_RegAddr,integer,4

//Trigger output level control
TriggerOutIO_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Triggerout IO Level
TriggerOutIO_Bit,bit,0

//Trigger output level duration
TriggerDurationUs_RegAddr,integer,4

//Trigger output level duration min
TriggerDurationUsMin_RegAddr,integer,4

//Trigger output level duration max
TriggerDurationUsMax_RegAddr,integer,4

//CMOS synchronous output enable control
CmosSync_RegAddr,struct,4,,DeviceCategory_RegAddr,RW,CMos Sync Ctrl
CmosSync_Bit,bit,0

//System time synchronization signal
TimeSyncReady_RegAddr,struct,4,,DeviceCategory_RegAddr,RW,Time Sync Ready Signal
cachable,NoCache
SyncReady_Bit,bit,0

//Statistics of the time taken to Capture
CaptureTimeStatisticUs_RegAddr,integer,4

//IR Undistortion enable
IR_Undistortion_En_RegAddr,struct,4,,DeviceCategory_RegAddr,RW,IR Undistortion En
invalidator,UserSetLoad
IR_Undistortion_En_Bit,bit,0

//Stream asynchronous mode selection
StreamAsync_RegAddr,integer,4

//The system time synchronization mode selection
TimeSyncType_RegAddr,integer,4

//Device temperature supports query
DeviceTemperatureInq_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Device Temperature Support Inq
DeviceTemperatureMainboardSupportInq_Bit,bit,0
DeviceTemperatureLeftSupportInq_Bit
DeviceTemperatureRightSupportInq_Bit
DeviceTemperatureTextureSupportInq_Bit
DeviceTemperatureLaserSupportInq_Bit
DeviceTemperatureIRFlashLightSupportInq_Bit
DeviceTemperatureColorFlashLightSupportInq_Bit
DeviceTemperatureLaser2SupportInq_Bit
DeviceTemperatureCpuCoreSupportInq_Bit

//temperature selector register
DeviceTemperatureSelector_RegAddr,integer,4
DeviceTemperatureValue_RegAddr,integer,4
DeviceTemperatureString_RegAddr,string,512

//Trigger register
DeviceTriggerSelectorInq_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Device Trigger Selector Support Inq
TriggerSelector_AcqStartInq_Bit,bit,0
TriggerSelector_AcqEndInq_Bit
TriggerSelector_AcqActiveInq_Bit
TriggerSelector_FrameStartInq_Bit
TriggerSelector_FrameEndInq_Bit
TriggerSelector_FrameActiveInq_Bit
TriggerSelector_FrameBStartInq_Bit
TriggerSelector_FrameBEndInq_Bit
TriggerSelector_FrameBActiveInq_Bit
TriggerSelector_LineStartInq_Bit
TriggerSelector_ExpStartInq_Bit
TriggerSelector_ExpEndInq_Bit
TriggerSelector_ExpActiveInq_Bit

DeviceTriggerSelector_RegAddr,integer,4
DeviceTriggerMode_RegAddr,integer,4
DeviceTriggerSoftware_RegAddr,integer,4


DeviceTriggerSourceInq_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Device Trigger Source Support Inq
TriggerSource0Inq_Bit,bit,0
TriggerSource1Inq_Bit
TriggerSource2Inq_Bit
TriggerSource3Inq_Bit
TriggerSource4Inq_Bit
TriggerSource5Inq_Bit
TriggerSource6Inq_Bit
TriggerSource7Inq_Bit
TriggerSourceSwInq_Bit

DeviceTriggerSource_RegAddr,integer,4

DeviceTriggerActivationInq_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Device Trigger Activation Support Inq
TriggerActivationRisingEdgeInq_Bit,bit,0
TriggerActivationFallingEdgeInq_Bit
TriggerActivationAnyEdgeInq_Bit
TriggerActivationLevelHighInq_Bit
TriggerActivationLevelLowInq_Bit

DeviceTriggerActivation_RegAddr,integer,4

DeviceSystemTime_RegAddr,integer,8

DeviceDataCompressType_RegAddr,integer,4

DeviceDataCompressTypeInq_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Device Data Compress Type Inq
DataCompressTypeNoneInq_Bit,bit,0
DataCompressTypeLZ4Inq_Bit

FirmwareUpdateControl_RegAddr,integer,4

Timestamp_RegAddr,integer,8

PostProcessing_AccelFrameTransformedEnabled_RegAddr,integer,4
PostProcessing_GyroFrameTransformedEnabled_RegAddr,integer,4
//const double         accelScaleMisalignment[9]  = { 1, 0, 0, 0, 1, 0, 0, 0, 1 };
//const double         accelBias[3] = { 0, 0, 0 };
//const double         gyroScaleMisalignment[9] = { 1, 0, 0, 0, 1, 0, 0, 0, 1 };
//const double         gyroBias[3] = { 0, 0, 0 };
//const double         imuToCamExtrinsics[16] = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 };
PostProcessing_CalibrateParams_RegAddr,byte array,512

//----------------------------DeviceCategory Register <Block2>-----------------//
//-------------------------------0x800000 - 0xC00000---------------------------//
//----------Device component function/parameter register address -------------//
PostProcessParams0_RegAddr,byte array,512,0x800000
PostProcessParams1_RegAddr,byte array,512

//Laser work mode supports query
LaserWorkModeInq_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Laser Work Mode
LaserWorkSyncSupportInq_Bit,bit,0
LaserWorkAlternansSupportInq_Bit
LaserWorkLeftSupportInq_Bit
LaserWorkRightSupportInq_Bit

//Laser work mode selection
LaserWorkMode_RegAddr,integer,4

//DEV_CRYPTO_MODE For RVS A/B/C Camera
DevCryptoMode_RegAddr,integer,4
//DEV_CRYPTO_KEY For RVS A/B/C Camera
DevCryptoKey_RegAddr,string,128

//laser_power_coef for laser safty
LaserPowerCoef_RegAddr,integer,4

//drv8899_currentr_val drv8899 drive current
Drv8899CurrVal_RegAddr,integer,4
//drv8899_skip_step drv889 skip step at ervery first image of on trip
Drv8899SkipStep_RegAddr,integer,4

//MOTOR_CURRENT for V Series
MotorLaserCurr_RegAddr,integer,4

//sgb_usr_max_image_channel, override max img num read from hardware
SGBUserMaxImgChn_RegAddr,integer,4

//Laser Power Coefficient Ampere Register Address
LaserPowerCoefAmpere_RegAddr,float,4

// When the motor is active, the DepthSgbmImageNumber configures the rotation period
MotorActive_RegAddr,integer,4

// Image information watermark
ImageWatermarkActive_RegAddr,integer,4

// Recmap Type 0:Non compressed, 1:compressed(default)
RecmapType_RegAddr,integer,4,0x800500,DeviceCategory_RegAddr,RO,Recmap Type


// Post process control parameter  supports query
PostProcessingFunctionInquiry_RegAddr,struct,4,,DeviceCategory_RegAddr,RO,Post Processing Function Inq
PostProcessingFunctionInquiry_SPKFilterSupportInq_Bit,bit,0
PostProcessingFunctionInquiry_TextureDistortionCorrectionSupportInq_Bit
PostProcessingFunctionInquiry_RGBDAlignSupportInq_Bit

// Speck filter param
//PostProcessing_SPKEnabled_RegAddr,integer,4
//PostProcessing_SPKMaxSize_RegAddr,integer,4
//PostProcessing_SPKMaxDiff_RegAddr,integer,4
//PostProcessing_SPKMaxPhysSize_RegAddr,float,4

// Texture distortion correction enabled
PostProcessing_TextureDistortionCorrectionEnabled_RegAddr,integer,4

// RGBD align enabled
PostProcessing_RGBDAlignEnabled_RegAddr,integer,4

//----------------------------DeviceCategory Register <Block3>-----------------//
//-------------------------------0xC00000 - 0xD00000---------------------------//
//---------------Device GenICam Descriptor Read Register Address --------------//
DeviceGenICamDescriptor_RegAddr,byte array,1048576,0xC00000,DeviceCategory_RegAddr,RO,Device Special GenICam XML Descriptor

//----------------------------DeviceCategory Register <Block4>-----------------//
//-------------------------------0xD00000 - 0xE00000---------------------------//
//---------------Device Digital IO Control Register Address -------------------//
DigitalIOControlLineSelectorInq_RegAddr,struct,4,0xd00000,DeviceCategory_RegAddr,RO,Device Digital IO Control Line Selector Inq
DigitalIOControl_Line0_Inq_Bit,bit,0
DigitalIOControl_Line1_Inq_Bit
DigitalIOControl_Line2_Inq_Bit
DigitalIOControl_Line3_Inq_Bit
DigitalIOControl_LinkTrigger0_Inq_Bit
DigitalIOControl_LinkTrigger1_Inq_Bit
DigitalIOControl_LinkTrigger2_Inq_Bit
DigitalIOControl_CC1_Inq_Bit
DigitalIOControl_CC2_Inq_Bit
DigitalIOControl_CC3_Inq_Bit
DigitalIOControl_CC4_Inq_Bit

DigitalIOControlLineModeInq_RegAddr,struct,4,0xd00004,DeviceCategory_RegAddr,RO,Device Digital IO Control Line Mode Inq
DigitalIOControl_Input_Inq_Bit,bit,0
DigitalIOControl_Output_Inq_Bit

DigitalIOControlLineSourceInq0_RegAddr,struct,4,0xd00008,DeviceCategory_RegAddr,RO,Device Digital IO Control Line Source Inq 1
DigitalIOControl_LineSource_Off_Inq_Bit,bit,0
DigitalIOControl_LineSource_UserOutput0_Inq_Bit
DigitalIOControl_LineSource_UserOutput1_Inq_Bit
DigitalIOControl_LineSource_UserOutput2_Inq_Bit
DigitalIOControl_LineSource_UserOutput3_Inq_Bit
DigitalIOControl_LineSource_AcquisitionTriggerWait_Inq_Bit
DigitalIOControl_LineSource_AcquisitionTrigger_Inq_Bit
DigitalIOControl_LineSource_AcquisitionTriggerMissed_Inq_Bit
DigitalIOControl_LineSource_AcquisitionActive_Inq_Bit
DigitalIOControl_LineSource_FrameTriggerWait_Inq_Bit
DigitalIOControl_LineSource_FrameTrigger_Inq_Bit
DigitalIOControl_LineSource_FrameTriggerMissed_Inq_Bit
DigitalIOControl_LineSource_FrameActive_Inq_Bit
DigitalIOControl_LineSource_ExposureActive_Inq_Bit
DigitalIOControl_LineSource_LineTriggerWait_Inq_Bit
DigitalIOControl_LineSource_LineTrigger_Inq_Bit
DigitalIOControl_LineSource_LineTriggerMissed_Inq_Bit
DigitalIOControl_LineSource_LineActive_Inq_Bit

DigitalIOControlLineSourceInq1_RegAddr,struct,4,0xd0000c,DeviceCategory_RegAddr,RO,Device Digital IO Control Line Source Inq 1
DigitalIOControl_LineSource_Counter0Active_Inq_Bit,bit,0
DigitalIOControl_LineSource_Counter1Active_Inq_Bit
DigitalIOControl_LineSource_Counter2Active_Inq_Bit
DigitalIOControl_LineSource_Timer0Active_Inq_Bit
DigitalIOControl_LineSource_Timer1Active_Inq_Bit
DigitalIOControl_LineSource_Timer2Active_Inq_Bit
DigitalIOControl_LineSource_Encoder0_Inq_Bit
DigitalIOControl_LineSource_Encoder1_Inq_Bit
DigitalIOControl_LineSource_Encoder2_Inq_Bit
DigitalIOControl_LineSource_LogicBlock0_Inq_Bit
DigitalIOControl_LineSource_LogicBlock1_Inq_Bit
DigitalIOControl_LineSource_LogicBlock2_Inq_Bit
DigitalIOControl_LineSource_SoftwareSignal0_Inq_Bit
DigitalIOControl_LineSource_SoftwareSignal1_Inq_Bit
DigitalIOControl_LineSource_SoftwareSignal2_Inq_Bit

DigitalIOControlUserOutputSelectorInq_RegAddr,struct,4,0xd00010,DeviceCategory_RegAddr,RO,Device Digital IO Control User Output Selector Inq
DigitalIOControl_UserOutput0_Inq_Bit,bit,0
DigitalIOControl_UserOutput1_Inq_Bit
DigitalIOControl_UserOutput2_Inq_Bit

DigitalIOControlFeatureInq_RegAddr,struct,4,0xd00014,DeviceCategory_RegAddr,RO,Device Digital IO Control Feature Inq,LineSelector
DigitalIOControl_LineMode_Inq_Bit,bit,0
DigitalIOControl_LineInverter_Inq_Bit
DigitalIOControl_LineStatus_Inq_Bit
DigitalIOControl_LineStatusAll_Inq_Bit
DigitalIOControl_LineSource_Inq_Bit
DigitalIOControl_LineSwFilter_Inq_Bit
DigitalIOControl_LineHwFilter_Inq_Bit
DigitalIOControl_UserOutputSelector_Inq_Bit
DigitalIOControl_UserOutputValue_Inq_Bit

LineSelector_RegAddr,integer,4

LineMode_RegAddr,integer,4

LineInverter_RegAddr,integer,4

LineStatus_RegAddr,integer,4

LineStatusAll_RegAddr,integer,4

LineSource_RegAddr,integer,4

LineSwFilter_RegAddr,integer,4

LineHwFilter_RegAddr,integer,4

UserOutputSelector_RegAddr,integer,4

UserOutputValue_RegAddr,integer,4

//----------------------------DeviceCategory Register <Block5>-----------------//
//-------------------------------0xF00000 - 0xFFFFFF---------------------------//
//---------------Device Log Control Register Address -------------------//
DeviceLogFuncInq_RegAddr,struct,4,0xF00000,DeviceCategory_RegAddr,RO,Device Log Control Func Inq
DeviceLogControl_Category_Inq_Bit,bit,0
DeviceSysLogEnable_Inq_Bit
DeviceLogOutputProtocol_Inq_Bit
DeviceLogRemoteIP_Inq_Bit
DeviceLogRemotePort_Inq_Bit
DeviceLogPriority_Inq_Bit

DeviceSysLogEnable_RegAddr,integer,4
DeviceLogOutputProtocol_RegAddr,integer,4
DeviceLogRemoteIP_RegAddr,integer,4
DeviceLogRemotePort_RegAddr,integer,4
DeviceLogPriority_RegAddr,integer,4

//---------------Event Control Register Address -------------------//
EventSelectorInq_RegAddr,struct,4,0xF10000,DeviceCategory_RegAddr,RO,Event Control Selector Inq
EventControl_PrimaryApplicationSwitch_Inq_Bit,bit,0
EventControl_LinkSpeedChange_Inq_Bit
EventControl_Test_Inq_Bit
EventControl_FrameTrigger_Inq_Bit
EventControl_FrameTriggerMissed_Inq_Bit
EventControl_Error_Inq_Bit
EventControl_IMU_Inq_Bit

EventSelector_RegAddr,integer,4
EventNotification_RegAddr,integer,4

//---------------Test Control Register Address -------------------//
TestEventGenerate_RegAddr,integer,4,0xF20000
TestEventMode_RegAddr,integer,4


TimeSyncTypeNone,integer,4,0
TimeSyncTypeHost,integer,4,1
TimeSyncTypeNTP,integer,4,2
TimeSyncTypePTP,integer,4,3
TimeSyncTypeCan,integer,4,4
TimeSyncTypePTPMaster,integer,4,5
////////////////
%xmlcode
<Enumeration Name="DeviceTimeSyncMode" NameSpace="Custom">
    <ToolTip>Select device time sync mode.</ToolTip>
    <Description>Select device time sync mode.</Description>
    <DisplayName>Device Timer Sync Mode Selector</DisplayName>
    <Visibility>Guru</Visibility>
    <pIsLocked>TLParamsLocked</pIsLocked>
    <ImposedAccessMode>RW</ImposedAccessMode>
    <EnumEntry Name="SyncTypeNone" NameSpace="Custom">
      <ToolTip>The device operates without time synchronization.</ToolTip>
      <Description>The device operates without time synchronization.</Description>
      <DisplayName>Time Sync Off</DisplayName>
      <pIsImplemented>TimeSyncNoneSupportInq_Bit</pIsImplemented>
      <Value>%TimeSyncTypeNone%</Value>
    </EnumEntry>
    <EnumEntry Name="SyncTypeHost" NameSpace="Custom">
      <ToolTip>The device enables automatic time synchronization with the host.</ToolTip>
      <Description>The device enables automatic time synchronization with the host.</Description>
      <DisplayName>Time Sync with Host</DisplayName>
      <pIsImplemented>TimeSyncHostSupportInq_Bit</pIsImplemented>
      <Value>%TimeSyncTypeHost%</Value>
    </EnumEntry>
    <EnumEntry Name="SyncTypeNTP" NameSpace="Custom">
      <ToolTip>The device enables automatic time synchronization with the NTP server.</ToolTip>
      <Description>The device enables automatic time synchronization with the NTP server.</Description>
      <DisplayName>Time Sync with NTP Server</DisplayName>
      <pIsImplemented>TimeSyncNTPSupportInq_Bit</pIsImplemented>
      <Value>%TimeSyncTypeNTP%</Value>
    </EnumEntry>
    <EnumEntry Name="SyncTypePTPSlave" NameSpace="Custom">
      <ToolTip>The device operates as a slave with automatic PTP (Precision Time Protocol) time synchronization enabled.</ToolTip>
      <Description>The device operates as a slave with automatic PTP (Precision Time Protocol) time synchronization enabled.</Description>
      <DisplayName>Time Sync as PTP Slave</DisplayName>
      <pIsImplemented>TimeSyncPTPSlaveSupportInq_Bit</pIsImplemented>
      <Value>%TimeSyncTypePTP%</Value>
    </EnumEntry>
    <EnumEntry Name="SyncTypeCAN" NameSpace="Custom">
      <ToolTip>Device Time Synchronization via CAN</ToolTip>
      <Description>Device Time Synchronization via CAN</Description>
      <DisplayName>Time Sync with CAN</DisplayName>
      <pIsImplemented>TimeSyncCanSupportInq_Bit</pIsImplemented>
      <Value>%TimeSyncTypeCan%</Value>
    </EnumEntry>
    <EnumEntry Name="SyncTypePTPMaster" NameSpace="Custom">
      <ToolTip>The device operates as a master with automatic PTP (Precision Time Protocol) time synchronization enabled.</ToolTip>
      <Description>The device operates as a master with automatic PTP (Precision Time Protocol) time synchronization enabled.</Description>
      <DisplayName>Time Sync as PTP Master</DisplayName>
      <pIsImplemented>TimeSyncPTPMasterSupportInq_Bit</pIsImplemented>
      <Value>%TimeSyncTypePTPMaster%</Value>
    </EnumEntry>
    <pValue>TimeSyncType_Reg</pValue>
</Enumeration>

<IntReg Name="TimeSyncType_Reg" NameSpace="Custom">
    <pAddress>DeviceCategory_RegAddr</pAddress>
    <pAddress>TimeSyncType_RegAddr</pAddress>
    <Length>4</Length>
    <AccessMode>RW</AccessMode>
    <pPort>Device</pPort>
    <Endianess>LittleEndian</Endianess>
</IntReg>

%enddef
)CSVDATA";

inline constexpr std::string_view kStreamCsv = R"CSVDATA(

//------------DEPTH/LEFT-IR/RIGHT-IR/COLOR Stream Register ------------------------//
//--------------------------DEPTH BASE ADDR:    0x02000000 ------------------------//
//--------------------------LEFT-IR BASE ADDR:  0x03000000 ------------------------//
//--------------------------RIGHT-IR BASE ADDR: 0x04000000 ------------------------//
//--------------------------COLOR BASE ADDR:    0x05000000 ------------------------//
// Block0 : 0x300000 - 0x400000 : Extended Register
// Block1 : 0x400000 - 0x800000 : Stream function/parameter register
// Block2 : 0x800000 - 0x820000 : Stream Inq & Pix Fmt & Binning Register
// Block3 : 0x820000 - 0x880000 : Stream ISP(AWB/AEC/GAIN...)
// Block4 : 0x880000 - 0xFFFFFF : Depth Stream specific Register(Scale/sgbm/sgpm)

//--------------------Extended Register <Block0>-----------//
//------------------------------0x300000 - 0x400000--------------------------------//
//Lens type:Standard lens, Fisheye lens...
//Defining future distortion parameter data format
CameraLensType_RegAddr,integer,4,0x300000

//--------------------Stream function/parameter register address <Block1>-----------//
//------------------------------0x400000 - 0x800000--------------------------------//
DeviceStreamEnable_RegAddr,struct,4,0x400000,SourceBaseAddress,RW,Device Stream status,SourceSelector
invalidator,UserSetLoad
StreamEnable_Bit,bit,0
IsNotValidComponentStreaming_Bit

DepthStreamEnable_RegAddr,struct,4,0x400000,DepthCategory_RegAddr,RW,Depth Stream status,SourceSelector
invalidator,UserSetLoad
DepthStreamEnable_Bit,bit,0

BinocularLeftStreamEnable_RegAddr,struct,4,0x400000,LeftCameraCategory_RegAddr,RW,Left IR Stream status
invalidator,UserSetLoad
BinocularLeftStreamEnable_Bit,bit,0

BinocularRightStreamEnable_RegAddr,struct,4,0x400000,RightCameraCategory_RegAddr,RW,Right IR Stream status
invalidator,UserSetLoad
BinocularRightStreamEnable_Bit,bit,0

IntensityStreamEnable_RegAddr,struct,4,0x400000,ColorCameraCategory_RegAddr,RW,Intensity Stream status
invalidator,UserSetLoad
IntensityStreamEnable_Bit,bit,0

//Calib data query
CalibrationDataConfig_RegAddr,struct,4,,SourceBaseAddress,RO,Stream Calibration Data Base Address,SourceSelector,SourceSelector
IntrinsicSupportInq_Bit,bit,0
Intrinsic2SupportInq_Bit
RotationSupportInq_Bit
DistortionSupportInq_Bit
ExtrinsicSupportInq_Bit
Extrinsic2SupportInq_Bit


IntrinsicWidth_RegAddr,integer,4
IntrinsicHeight_RegAddr,integer,4
Intrinsic_RegAddr,byte array,72
Intrinsic2_RegAddr,byte array,72
Rotation_RegAddr,byte array,72
Distortion_RegAddr,byte array,96
Extrinsic_RegAddr,byte array,128
Extrinsic2_RegAddr,byte array,128
Q_4x4_RegAddr,byte array,128,,hidden

//---------------Stream Inq & Pix Fmt & Binning Register <Block2>-------------------//
//-------------------------------0x800000 - 0x820000--------------------------------//
//Color/Left/Right Camera/Phase supports query
StreamFunctionInq_RegAddr,struct,4,0x810000,SourceBaseAddress,RO,Stream Func Inq,SourceSelector
invalidator,PixelFormat
StreamISP_AWB_SupportInq_Bit,bit,0
StreamISP_AEC_SupportInq_Bit
StreamISP_AEC_AOISupportInq_Bit
StreamISP_ExposureTimeCtrl_SupportInq_Bit
StreamISP_AnalogGainCtrl_SupportInq_Bit
StreamISP_DigitalGainCtrl_SupportInq_Bit
StreamISP_RedGainCtrl_SupportInq_Bit
StreamISP_GreenGainCtrl_SupportInq_Bit
StreamISP_BlueGainCtrl_SupportInq_Bit
StreamISP_TargetY_SupportInq_Bit
StreamISP_HDR_SupportInq_Bit
IRLeftStreamTofSupportInq_Bit
StreamISP_AEC_Limit_SupportInq_Bit
StreamISP_AGC_SupportInq_Bit
StreamISP_MeteringMode_SupportInq_Bit


//Depth stream function query
DepthStreamFunctionInq_RegAddr,struct,4,,DepthCategory_RegAddr,RO,Depth Stream Func Inq
DepthStreamScaleUnitSupportInq_Bit,bit,0
DepthStreamScaleUnitLocked_Bit
DepthStreamSGBMSupportInq_Bit
DepthStreamSGPMSupportInq_Bit
DepthStreamTofSupportInq_Bit
DepthQualityLowSupportInq_Bit
DepthQualityMediumSupportInq_Bit
DepthQualityHighSupportInq_Bit
DepthRegisterToColorEnableInq_Bit

//stream format Idx
//StreamPixelFormatIdx_RegAddr,integer,4

//stream format Idx min
//StreamPixelFormatIdxMin_RegAddr,integer,4

//stream format Idx max
//StreamPixelFormatIdxMax_RegAddr,integer,4

//stream format
//StreamPixelFormat_RegAddr,integer,4

//stream format supports query 0
StreamPixelFormatInq0_RegAddr,struct,4,,SourceBaseAddress,RO,Stream PixelFormat Inquiry 0 Register,SourceSelector
//Mono8
Mono8_Inq_Bit,bit,0
//BayerGB8
BayerGB8_Inq_Bit
//BayerBG8
BayerBG8_Inq_Bit
//BayerGR8
BayerGR8_Inq_Bit
//BayerRG8
BayerRG8_Inq_Bit

//Mono10  byte1:byte2 =  [p p p p p p 9 8]:[7 6 5 4 3 2 1 0]
Mono10_Inq_Bit
//BayerGB10
BayerGB10_Inq_Bit
//BayerBG10
BayerBG10_Inq_Bit
//BayerGR10
BayerGR10_Inq_Bit
//BayerRG10
BayerRG10_Inq_Bit

//Mono12  byte1:byte2 = [p p p p 11 10 9 8]:[7 6 5 4 3 2 1 0]
Mono12_Inq_Bit
//BayerGB12
BayerGB12_Inq_Bit
//BayerBG12
BayerBG12_Inq_Bit
//BayerGR12
BayerGR12_Inq_Bit
//BayerRG12
BayerRG12_Inq_Bit

//Mono14 byte1:byte2 = [p p 13 12 11 10 9 8]:[7 6 5 4 3 2 1 0]
Mono14_Inq_Bit
//BayerGB14
BayerGB14_Inq_Bit
//BayerBG14
BayerBG14_Inq_Bit
//BayerGR14
BayerGR14_Inq_Bit
//BayerRG14
BayerRG14_Inq_Bit

//Mono16
Mono16_Inq_Bit
//BayerGB16
BayerGB16_Inq_Bit
//BayerBG16
BayerBG16_Inq_Bit
//BayerGR16
BayerGR16_Inq_Bit
//BayerRG16
BayerRG16_Inq_Bit

//RGB8
RGB8_Inq_Bit
//BGR8
BGR8_Inq_Bit

//YUV422_8
YUV422_8_YUYV_Inq_Bit
//YUV422_8_UYVY
YUV422_8_UYVY_Inq_Bit

//stream format supports query 1
StreamPixelFormatInq1_RegAddr,struct,4,,SourceBaseAddress,RO,Stream PixelFormat Inquiry 1 Register,SourceSelector
//Coord3D_C16 : depth image
Coord3D_C16_Inq_Bit,bit,0
//Coord3D_ABC16 : xyz48
Coord3D_ABC16_Inq_Bit
//Coord3D_ABC32f : point3d
Coord3D_ABC32f_Inq_Bit

//Mono10p
Mono10p_Inq_Bit
//BayerGB10p
BayerGB10p_Inq_Bit
//BayerBG10p
BayerBG10p_Inq_Bit
//BayerGR10p
BayerGR10p_Inq_Bit
//BayerRG10p
BayerRG10p_Inq_Bit
//Mono12p
Mono12p_Inq_Bit
//BayerGB12p
BayerGB12p_Inq_Bit
//BayerBG12p
BayerBG12p_Inq_Bit
//BayerGR12p
BayerGR12p_Inq_Bit
//BayerRG12p
BayerRG12p_Inq_Bit
//YCbCr420_8_YY_CbCr_Planar
YCbCr420_8_YY_CbCr_Planar_Inq_Bit
//YCbCr420_8_YY_CrCb_Planar
YCbCr420_8_YY_CrCb_Planar_Inq_Bit
//YCbCr420_8_YY_CbCr_Semiplanar
YCbCr420_8_YY_CbCr_Semiplanar_Inq_Bit
//YCbCr420_8_YY_CrCb_Semiplanar
YCbCr420_8_YY_CrCb_Semiplanar_Inq_Bit

//JPEG
JPEG_Inq_Bit
//TofIR_FourGroup_Mono16
TofIR_FourGroup_Mono16_Inq_Bit

//stream format
StreamPixelFormat_RegAddr,integer,4

//Resolution ReadyOnly
StreamResolution_Width_RegAddr,integer,4
StreamResolution_Height_RegAddr,integer,4

//This is a placeholder register that serves as a replacement for the PayLoad register location. 
//The original payload register is now relocated to the Device.CSV file."
StreamPlaceholder1_RegAddr,integer,4


//Binning query register
StreamBinningInq_RegAddr,struct,4,,SourceBaseAddress,RO,Stream Binning Inquiry Register,SourceSelector
invalidator,PixelFormat
Binning_1_Inq,bit,0
Binning_2_Inq
Binning_3_Inq
Binning_4_Inq

//Binning mode setting
Binning_RegAddr,integer,4


StreamPixelSize_regAddr,integer,4
//Region of interest
RegionSelector_RegAddr,integer,4
RegionMode_RegAddr,integer,4
RegionDestination_RegAddr,integer,4
RegionIDValue_RegAddr,integer,4
RegionWidth_regAddr,integer,4
RegionHeight_regAddr,integer,4
RegionOffsetX_regAddr,integer,4
RegionOffsetY_regAddr,integer,4
RegionReserve_RegAddr,byte array,320

//---------------Stream ISP(AWB/AEC/GAIN...) Register <Block3> ---------------------//
//-------------------------------0x820000 - 0x880000--------------------------------//
//Stream AWB switch
StreamAWBEnable_RegAddr,integer,4,0x820000

//Stream AEC switch
StreamAECEnable_RegAddr,integer,4

//Stream exposure time
StreamExposureTime_RegAddr,float,4

//Stream exposure time min
StreamExposureTimeMin_RegAddr,float,4

//Stream exposure time max
StreamExposureTimeMax_RegAddr,float,4

//The actual offset address corresponding to the current stream index, with multiple consecutive uint32_t values storing the offset addresses of different streams respectively.
//DepthCategory_RegAddr / ColorCameraCategory_RegAddr / LeftCameraCategory_RegAddr/ RightCameraCategory_RegAddr
CurrentGain_BaseRegAddr,float,0
StreamAnalogGain_RegAddr,float,4
StreamAnalogGainMin_RegAddr,float,4
StreamAnalogGainMax_RegAddr,float,4

StreamDigitalGain_BaseRegAddr,float,4
StreamDigitalGainMin_RegAddr,float,4
StreamDigitalGainMax_RegAddr,float,4

StreamRedGain_RegAddr,float,4
StreamRedGainMin_RegAddr,float,4
StreamRedGainMax_RegAddr,float,4

StreamGreenGain_RegAddr,float,4
StreamGreenGainMin_RegAddr,float,4
StreamGreenGainMax_RegAddr,float,4

StreamBlueGain_RegAddr,float,4
StreamBlueGainMin_RegAddr,float,4
StreamBlueGainMax_RegAddr,float,4

StreamResvGain_RegAddr,byte array,48

%xmlcode
<Enumeration Name="GainSelector" NameSpace="Standard">
  <!-- Optional element -->
  <ToolTip>Selects which Gain is controlled by the various Gain features.</ToolTip>
  <Description>Selects which Gain is controlled by the various Gain features.</Description>
  <DisplayName>Gain Selector</DisplayName>
  <Visibility>Beginner</Visibility>
  <pIsImplemented>StreamISP_GainCtrl_SupportInq_Int</pIsImplemented>
  <ImposedAccessMode>RW</ImposedAccessMode>
  <Streamable>Yes</Streamable>
  <EnumEntry Name="AnalogAll" NameSpace="Standard">
    <ToolTip>Gain will be applied to all analog channels or taps.</ToolTip>
    <Description>Gain will be applied to all analog channels or taps.</Description>
    <DisplayName>Analog All</DisplayName>
    <pIsImplemented>StreamISP_AnalogGainCtrl_SupportInq_Bit</pIsImplemented>
    <!--<pIsAvailable>GainUnLock_Inq</pIsAvailable>-->
    <Value>0</Value>
  </EnumEntry>
  <EnumEntry Name="DigitalAll" NameSpace="Standard">
    <ToolTip>Gain will be applied to all digital channels or taps.</ToolTip>
    <Description>Gain will be applied to all digital channels or taps.</Description>
    <DisplayName>Digital All</DisplayName>
    <pIsImplemented>StreamISP_DigitalGainCtrl_SupportInq_Bit</pIsImplemented>
    <!--<pIsAvailable>GainUnLock_Inq</pIsAvailable>-->
    <Value>1</Value>
  </EnumEntry>
  <EnumEntry Name="DigitalRed" NameSpace="Standard">
    <ToolTip>Gain will be applied to the red digital channel.</ToolTip>
    <Description>Gain will be applied to the red digital channel.</Description>
    <DisplayName>Digital Red</DisplayName>
    <pIsImplemented>StreamISP_RedGainCtrl_SupportInq_Bit</pIsImplemented>
    <!--<pIsAvailable>GainUnLock_Inq</pIsAvailable>-->
    <Value>2</Value>
  </EnumEntry>
    <EnumEntry Name="DigitalGreen" NameSpace="Standard">
    <ToolTip>Gain will be applied to the green digital channel.</ToolTip>
    <Description>Gain will be applied to the green digital channel.</Description>
    <DisplayName>Digital Green</DisplayName>
    <pIsImplemented>StreamISP_GreenGainCtrl_SupportInq_Bit</pIsImplemented>
    <!--<pIsAvailable>GainUnLock_Inq</pIsAvailable>-->
    <Value>3</Value>
  </EnumEntry>
  <EnumEntry Name="DigitalBlue" NameSpace="Standard">
    <ToolTip>Gain will be applied to the blue digital channel.</ToolTip>
    <Description>Gain will be applied to the blue digital channel.</Description>
    <DisplayName>Digital Blue</DisplayName>
    <pIsImplemented>StreamISP_BlueGainCtrl_SupportInq_Bit</pIsImplemented>
    <!--<pIsAvailable>GainUnLock_Inq</pIsAvailable>-->
    <Value>4</Value>
  </EnumEntry>
  <pValue>CurrentGain_BaseIdxReg</pValue>
  <pSelected>Gain</pSelected>
</Enumeration>

<IntSwissKnife Name="AECDisable_Inq">
  <pVariable Name="CTRL">StreamAECEnable_Reg</pVariable>
  <Formula>(CTRL = 0)</Formula>
</IntSwissKnife>

<IntSwissKnife Name="AWBDisable_Inq">
  <pVariable Name="CTRL">StreamAWBEnable_Reg</pVariable>
  <Formula>(CTRL = 0)</Formula>
</IntSwissKnife>

<Integer Name="CurrentGain_BaseIdxReg" NameSpace="Custom">
  <ImposedAccessMode>RW</ImposedAccessMode>
  <Value>0</Value>
</Integer>

<Integer Name="CurrentGainAddress_Reg">
  <Value>0</Value>
</Integer>

<Integer Name="CurrentGainMinAddress_Reg">
  <Value>4</Value>
</Integer>

<Integer Name="CurrentGainMaxAddress_Reg">
  <Value>8</Value>
</Integer>

<!--Gain-->
<Float Name="Gain" NameSpace="Standard">
  <ToolTip>Controls the selected gain as an absolute physical value.</ToolTip>
  <Description>Controls the selected gain as an absolute physical value. This is an amplification factor applied to the video signal.</Description>
  <DisplayName>Gain</DisplayName>
  <pIsImplemented>StreamISP_GainCtrl_SupportInq_Int</pIsImplemented>
  <pIsAvailable>GainUnLock_Inq</pIsAvailable>
  <ImposedAccessMode>RW</ImposedAccessMode>
  <Streamable>Yes</Streamable>
  <pValue>GainAbsVal_Float</pValue>
  <pMin>GainAbsMinInq_Float</pMin>
  <pMax>GainAbsMaxInq_Float</pMax>
</Float>

<IntSwissKnife Name="StreamISP_GainCtrl_SupportInq_Int">
  <pVariable Name="AnalogGainInq">StreamISP_AnalogGainCtrl_SupportInq_Bit</pVariable>
  <pVariable Name="DigitalGainInq">StreamISP_DigitalGainCtrl_SupportInq_Bit</pVariable>
  <pVariable Name="RedGainInq">StreamISP_RedGainCtrl_SupportInq_Bit</pVariable>
  <pVariable Name="GreenGainInq">StreamISP_GreenGainCtrl_SupportInq_Bit</pVariable>
  <pVariable Name="BlueGainInq">StreamISP_BlueGainCtrl_SupportInq_Bit</pVariable>
  <Formula>(AnalogGainInq + DigitalGainInq + RedGainInq + GreenGainInq + BlueGainInq)?1:0</Formula>
</IntSwissKnife>

<FloatReg Name="GainAbsVal_Float" NameSpace="Custom">
  <pAddress>CurrentGain_Offset</pAddress>
  <pAddress>CurrentGainAddress_Reg</pAddress>
  <Length>4</Length>
  <AccessMode>RW</AccessMode>
  <pPort>Device</pPort>   
  <pInvalidator>SourceSelector</pInvalidator>
  <pInvalidator>GainSelector</pInvalidator>
  <pInvalidator>ExposureAuto</pInvalidator>
  <pInvalidator>BalanceWhiteAuto</pInvalidator>
  <pInvalidator>UserSetLoad</pInvalidator>
  <Endianess>LittleEndian</Endianess>
</FloatReg>

<FloatReg Name="GainAbsMinInq_Float" NameSpace="Custom">
  <pAddress>CurrentGain_Offset</pAddress>
  <pAddress>CurrentGainMinAddress_Reg</pAddress>
  <Length>4</Length>
  <AccessMode>RO</AccessMode>
  <pPort>Device</pPort>
  <pInvalidator>SourceSelector</pInvalidator>
  <pInvalidator>GainSelector</pInvalidator>
  <Endianess>LittleEndian</Endianess>
</FloatReg>

<FloatReg Name="GainAbsMaxInq_Float" NameSpace="Custom">
  <pAddress>CurrentGain_Offset</pAddress>
  <pAddress>CurrentGainMaxAddress_Reg</pAddress>
  <Length>4</Length>
  <AccessMode>RO</AccessMode>
  <pPort>Device</pPort>
  <pInvalidator>SourceSelector</pInvalidator>
  <pInvalidator>GainSelector</pInvalidator>
  <Endianess>LittleEndian</Endianess>
</FloatReg>

%enddef

//Stream Target brightness
StreamTargetY_RegAddr,integer,4

//Stream Target brightness min
StreamTargetYMin_RegAddr,integer,4

//Stream Target brightness max
StreamTargetYMax_RegAddr,integer,4

//Stream HDR enable
StreamHDR_Enable_RegAddr,integer,4

//Stream HDR data
StreamHDR_RegAddr,byte array,2048

//Stream HDR data size
StreamHDRDataSize_RegAddr,integer,4

//Stream AEC AOI <x.y.w.h>
StreamISP_AEC_AOIOffsetX_RegAddr,integer,4
StreamISP_AEC_AOIOffsetY_RegAddr,integer,4
StreamISP_AEC_AOIWidth_RegAddr,integer,4
StreamISP_AEC_AOIHeight_RegAddr,integer,4
StreamISP_AEC_AOIWidthMin_RegAddr,integer,4
StreamISP_AEC_AOIHeightMin_RegAddr,integer,4

//IR AEC min exporetime
StreamAECExposureTimeMin_RegAddr,float,4
//IR AEC max exporetime
StreamAECExposureTimeMax_RegAddr,float,4

//Stream HDR exposure time min/max same as standard exposuretime, max support 5 group Now
StreamHDRExposureCnt_RegAddr,integer,4
StreamHDRExposureCntMax_RegAddr,integer,4
StreamHDRExposureTime2_RegAddr,float,4
StreamHDRExposureTime3_RegAddr,float,4
StreamHDRExposureTime4_RegAddr,float,4
StreamHDRExposureTime5_RegAddr,float,4

//Stream AGC link ExposureAuto switch
StreamAGCLinkExposureAuto_RegAddr,integer,4

//Stream AE metering mode
StreamAEMeteringLowThr_RegAddr,integer,4
StreamAEMeteringHighThr_RegAddr,integer,4

//-----------Depth Stream specific Register(Scale/sgbm/sgpm) <Block4>---------------//
//-------------------------------0x880000 - 0xFFFFFF--------------------------------//
//Depth Scale Unit
DepthStreamScale_RegAddr,float,4,0x880000
DepthStreamScaleMin_RegAddr,float,4
DepthStreamScaleMax_RegAddr,float,4

//Depth SGBM parameter
DepthStreamSgbmWithP1_RegAddr,integer,4
DepthStreamSgbmPipeChNum_RegAddr,integer,4
DepthStreamSgbmWCompress_RegAddr,integer,4

//TY_INT_SGBM_IMAGE_NUM
DepthStreamSgbmImageNumber_RegAddr,integer,4
DepthStreamSgbmImageNumberMin_RegAddr,integer,4
DepthStreamSgbmImageNumberMax_RegAddr,integer,4

//TY_INT_SGBM_DISPARITY_NUM
DepthStreamSgbmDisparityNumber_RegAddr,integer,4
DepthStreamSgbmDisparityNumberMin_RegAddr,integer,4
DepthStreamSgbmDisparityNumberMax_RegAddr,integer,4

//TY_INT_SGBM_DISPARITY_OFFSET
DepthStreamSgbmDisparityOffset_RegAddr,integer,4
DepthStreamSgbmDisparityOffsetMin_RegAddr,integer,4
DepthStreamSgbmDisparityOffsetMax_RegAddr,integer,4

//TY_INT_SGBM_MATCH_WIN_HEIGHT
DepthStreamSgbmMatchWinHeight_RegAddr,integer,4
DepthStreamSgbmMatchWinHeightMin_RegAddr,integer,4
DepthStreamSgbmMatchWinHeightMax_RegAddr,integer,4

//TY_INT_SGBM_SEMI_PARAM_P1
DepthStreamSgbmSemiParamP1_RegAddr,integer,4
DepthStreamSgbmSemiParamP1Min_RegAddr,integer,4
DepthStreamSgbmSemiParamP1Max_RegAddr,integer,4

//TY_INT_SGBM_SEMI_PARAM_P2
DepthStreamSgbmSemiParamP2_RegAddr,integer,4
DepthStreamSgbmSemiParamP2Min_RegAddr,integer,4
DepthStreamSgbmSemiParamP2Max_RegAddr,integer,4

//TY_INT_SGBM_UNIQUE_FACTOR
DepthStreamSgbmUniqueFactor_RegAddr,integer,4
DepthStreamSgbmUniqueFactorMin_RegAddr,integer,4
DepthStreamSgbmUniqueFactorMax_RegAddr,integer,4

//TY_INT_SGBM_UNIQUE_ABSDIFF
DepthStreamSgbmUniqueAbsDiff_RegAddr,integer,4
DepthStreamSgbmUniqueAbsDiffMin_RegAddr,integer,4
DepthStreamSgbmUniqueAbsDiffMax_RegAddr,integer,4

//TY_INT_SGBM_UNIQUE_MAX_COST
DepthStreamSgbmUniqueMaxCost_RegAddr,integer,4
DepthStreamSgbmUniqueMaxCostMin_RegAddr,integer,4
DepthStreamSgbmUniqueMaxCostMax_RegAddr,integer,4

//TY_BOOL_SGBM_HFILTER_HALF_WIN
DepthStreamSgbmHFilterHalfWin_RegAddr,integer,4

//TY_INT_SGBM_MATCH_WIN_WIDTH
DepthStreamSgbmMatchWinWidth_RegAddr,integer,4
DepthStreamSgbmMatchWinWidthMin_RegAddr,integer,4
DepthStreamSgbmMatchWinWidthMax_RegAddr,integer,4

//TY_BOOL_SGBM_MEDFILTER
DepthStreamSgbmMedFilter_RegAddr,integer,4

//TY_BOOL_SGBM_LRC
DepthStreamSgbmLRC_RegAddr,integer,4

//TY_INT_SGBM_LRC_DIFF
DepthStreamSgbmLRCDiff_RegAddr,integer,4
DepthStreamSgbmLRCDiffMin_RegAddr,integer,4
DepthStreamSgbmLRCDiffMax_RegAddr,integer,4

//TY_INT_SGBM_MEDFILTER_THRESH
DepthStreamSgbmMedFilterThresh_RegAddr,integer,4
DepthStreamSgbmMedFilterThreshMin_RegAddr,integer,4
DepthStreamSgbmMedFilterThreshMax_RegAddr,integer,4

//TY_INT_SGBM_SEMI_PARAM_P1_SCALE
DepthStreamSgbmSemiParamP1Scale_RegAddr,integer,4
DepthStreamSgbmSemiParamP1ScaleMin_RegAddr,integer,4
DepthStreamSgbmSemiParamP1ScaleMax_RegAddr,integer,4

//TY_INT_SGPM_PHASE_NUM
DepthStreamSgpmPhaseNumber_RegAddr,integer,4
DepthStreamSgpmPhaseNumberMin_RegAddr,integer,4
DepthStreamSgpmPhaseNumberMax_RegAddr,integer,4

//TY_INT_SGPM_NORMAL_PHASE_SCALE
DepthStreamSgpmPhaseScale_RegAddr,integer,4
DepthStreamSgpmPhaseScaleMin_RegAddr,integer,4
DepthStreamSgpmPhaseScaleMax_RegAddr,integer,4

//TY_INT_SGPM_NORMAL_PHASE_OFFSET
DepthStreamSgpmPhaseOffset_RegAddr,integer,4
DepthStreamSgpmPhaseOffsetMin_RegAddr,integer,4
DepthStreamSgpmPhaseOffsetMax_RegAddr,integer,4

//TY_INT_SGPM_REF_PHASE_SCALE
DepthStreamSgpmReferencePhaseScale_RegAddr,integer,4
DepthStreamSgpmReferencePhaseScaleMin_RegAddr,integer,4
DepthStreamSgpmReferencePhaseScaleMax_RegAddr,integer,4

//TY_INT_SGPM_REF_PHASE_OFFSET
DepthStreamSgpmReferencePhaseOffset_RegAddr,integer,4
DepthStreamSgpmReferencePhaseOffsetMin_RegAddr,integer,4
DepthStreamSgpmReferencePhaseOffsetMax_RegAddr,integer,4

//TY_FLOAT_SGPM_EPI_HS
DepthStreamSgpmEpipolarConstraintPatternScale_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintPatternScaleMin_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintPatternScaleMax_RegAddr,integer,4

//TY_INT_SGPM_EPI_HF
DepthStreamSgpmEpipolarConstraintPatternOffset_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintPatternOffsetMin_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintPatternOffsetMax_RegAddr,integer,4

//TY_BOOL_SGPM_EPI_EN
DepthStreamSgpmEpipolarConstraintEnable_RegAddr,integer,4

//TY_INT_SGPM_EPI_CH0
DepthStreamSgpmEpipolarConstraintChan0_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintChan0Min_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintChan0Max_RegAddr,integer,4

//TY_INT_SGPM_EPI_CH1
DepthStreamSgpmEpipolarConstraintChan1_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintChan1Min_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintChan1Max_RegAddr,integer,4

//TY_INT_SGPM_EPI_THRESH
DepthStreamSgpmEpipolarConstraintThresh_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintThreshMin_RegAddr,integer,4
DepthStreamSgpmEpipolarConstraintThreshMax_RegAddr,integer,4

//TY_BOOL_SGPM_ORDER_FILTER_EN
DepthStreamSgpmPhaseOrderFilterEnable_RegAddr,integer,4

//TY_INT_SGPM_ORDER_FILTER_CHN
DepthStreamSgpmPhaseOrderFilterChannel_RegAddr,integer,4
DepthStreamSgpmPhaseOrderFilterChannelMin_RegAddr,integer,4
DepthStreamSgpmPhaseOrderFilterChannelMax_RegAddr,integer,4

//TY_INT_DEPTH_MIN_MM
DepthStreamMinDepthInMMOutput_RegAddr,integer,4
DepthStreamMinDepthInMMOutputMin_RegAddr,integer,4
DepthStreamMinDepthInMMOutputMax_RegAddr,integer,4

//TY_INT_DEPTH_MAX_MM
DepthStreamMaxDepthInMMOutput_RegAddr,integer,4
DepthStreamMaxDepthInMMOutputMin_RegAddr,integer,4
DepthStreamMaxDepthInMMOutputMax_RegAddr,integer,4

//TY_INT_SGBM_TEXTURE_OFFSET
DepthStreamSgbmTextureFilterValueOffset_RegAddr,integer,4
DepthStreamSgbmTextureFilterValueOffsetMin_RegAddr,integer,4
DepthStreamSgbmTextureFilterValueOffsetMax_RegAddr,integer,4

//TY_INT_SGBM_TEXTURE_THRESH
DepthStreamSgbmTextureFilterThreshold_RegAddr,integer,4
DepthStreamSgbmTextureFilterThresholdMin_RegAddr,integer,4
DepthStreamSgbmTextureFilterThresholdMax_RegAddr,integer,4

//TY_STRUCT_PHC_GROUP_ATTR
DepthStreamPhaseComputeGroupAttribute_RegAddr,byte array,520

DepthStreamSgbmSaturateFilterEnable_RegAddr,integer,4

DepthStreamSgbmSaturateFilterVal_RegAddr,integer,4
DepthStreamSgbmSaturateFilterValMin_RegAddr,integer,4
DepthStreamSgbmSaturateFilterValMax_RegAddr,integer,4

DepthStreamSgbmSaturateFilterBlurSize_RegAddr,integer,4
DepthStreamSgbmSaturateFilterBlurSizeMin_RegAddr,integer,4
DepthStreamSgbmSaturateFilterBlurSizeMax_RegAddr,integer,4

DepthStreamSgbmSaturateFilterErodeSize_RegAddr,integer,4
DepthStreamSgbmSaturateFilterErodeSizeMin_RegAddr,integer,4
DepthStreamSgbmSaturateFilterErodeSizeMax_RegAddr,integer,4

DepthStreamSgbmSaturateFilterDilateSize_RegAddr,integer,4
DepthStreamSgbmSaturateFilterDilateSizeMin_RegAddr,integer,4
DepthStreamSgbmSaturateFilterDilateSizeMax_RegAddr,integer,4

DepthStreamSgbmTextureFilterEnable_RegAddr,integer,4

DepthStreamSgbmTextureFilterWindowSize_RegAddr,integer,4
DepthStreamSgbmTextureFilterWindowSizeMin_RegAddr,integer,4
DepthStreamSgbmTextureFilterWindowSizeMax_RegAddr,integer,4

DepthStreamSgbmTextureFilterMaxDistance_RegAddr,integer,4
DepthStreamSgbmTextureFilterMaxDistanceMin_RegAddr,integer,4
DepthStreamSgbmTextureFilterMaxDistanceMax_RegAddr,integer,4

//Magpie phase param (0 ~ 0x7fff -> 0 ~ 2Pi)
DepthStreamSgpmOutlierFilterPhaseThreshold_RegAddr,integer,4
DepthStreamSgpmOutlierFilterPhaseThresholdMin_RegAddr,integer,4
DepthStreamSgpmOutlierFilterPhaseThresholdMax_RegAddr,integer,4

//Magpie phase param(0 ~ (1 << valid_bits)  - 1)
DepthStreamSgpmAmplitudeThreshold_RegAddr,float,4
DepthStreamSgpmAmplitudeThresholdMin_RegAddr,float,4
DepthStreamSgpmAmplitudeThresholdMax_RegAddr,float,4

//Magpie post proc param, unit mm
DepthStreamSpeckleThresh_RegAddr,integer,4
DepthStreamSpeckleThreshMin_RegAddr,integer,4
DepthStreamSpeckleThreshMax_RegAddr,integer,4

//Magpie post proc param, unit pixel 
DepthStreamSpeckleMaxSize_RegAddr,integer,4
DepthStreamSpeckleMaxSizeMin_RegAddr,integer,4
DepthStreamSpeckleMaxSizeMax_RegAddr,integer,4

//Magpie phase match diff (0 ~ 0x7fff -> 0 ~ 2Pi)
DepthStreamSgpmMaxPhaseDiff_RegAddr,integer,4
DepthStreamSgpmMaxPhaseDiffMin_RegAddr,integer,4
DepthStreamSgpmMaxPhaseDiffMax_RegAddr,integer,4

//Start Of Magpie Depth/disparity post-filter(DT filter)
DepthStreamSgpmDepthFilterEnable_RegAddr,integer,4

DepthStreamSgpmDepthFilterGradScale_RegAddr,integer,4
DepthStreamSgpmDepthFilterGradScaleMin_RegAddr,integer,4
DepthStreamSgpmDepthFilterGradScaleMax_RegAddr,integer,4

DepthStreamSgpmDepthFilterRadius_RegAddr,integer,4
DepthStreamSgpmDepthFilterRadiusMin_RegAddr,integer,4
DepthStreamSgpmDepthFilterRadiusMax_RegAddr,integer,4

DepthStreamSgpmDepthFilterSigmaS_RegAddr,float,4
DepthStreamSgpmDepthFilterSigmaSMin_RegAddr,float,4
DepthStreamSgpmDepthFilterSigmaSMax_RegAddr,float,4

DepthStreamSgpmDepthFilterSigmaD_RegAddr,float,4
DepthStreamSgpmDepthFilterSigmaDMin_RegAddr,float,4
DepthStreamSgpmDepthFilterSigmaDMax_RegAddr,float,4

DepthStreamSgpmDepthFilterSigmaR_RegAddr,float,4
DepthStreamSgpmDepthFilterSigmaRMin_RegAddr,float,4
DepthStreamSgpmDepthFilterSigmaRMax_RegAddr,float,4
//End Of Magpie Depth/disparity post-filter(DT filter)

DepthStreamSgbmSpeckleFilterEnable_RegAddr,integer,4

DepthStreamSgbmSpeckleFilterSize_RegAddr,integer,4
DepthStreamSgbmSpeckleFilterSizeMin_RegAddr,integer,4
DepthStreamSgbmSpeckleFilterSizeMax_RegAddr,integer,4

DepthStreamSgbmSpeckleFilterMaxDiff_RegAddr,float,4
DepthStreamSgbmSpeckleFilterMaxDiffMin_RegAddr,float,4
DepthStreamSgbmSpeckleFilterMaxDiffMax_RegAddr,float,4

DepthStreamSgbmSpeckleFilterMaxPhysicalSize_RegAddr,float,4
DepthStreamSgbmSpeckleFilterMaxPhysicalSizeMin_RegAddr,float,4
DepthStreamSgbmSpeckleFilterMaxPhysicalSizeMax_RegAddr,float,4

DepthStreamRegisterToColorEnable_RegAddr,integer,4


//TY_INT_FILTER_THRESHOLD
DepthStreamTofFilterThreshold_RegAddr,integer,4,0x890000
DepthStreamTofFilterThresholdMin_RegAddr,integer,4
DepthStreamTofFilterThresholdMax_RegAddr,integer,4

//TY_INT_TOF_CHANNEL
DepthStreamTofChannel_RegAddr,integer,4
DepthStreamTofChannelMin_RegAddr,integer,4
DepthStreamTofChannelMax_RegAddr,integer,4

//TY_INT_TOF_MODULATION_THRESHOLD
DepthStreamTofModulationThreshold_RegAddr,integer,4
DepthStreamTofModulationThresholdMin_RegAddr,integer,4
DepthStreamTofModulationThresholdMax_RegAddr,integer,4

//TY_ENUM_DEPTH_QUALITY
DepthStreamTofDepthQuality_RegAddr,integer,4
DepthStreamTofDepthQualityMin_RegAddr,integer,4
DepthStreamTofDepthQualityMax_RegAddr,integer,4

//TY_INT_TOF_HDR_RATIO
DepthStreamTofHdrRatio_RegAddr,integer,4
DepthStreamTofHdrRatioMin_RegAddr,integer,4
DepthStreamTofHdrRatioMax_RegAddr,integer,4

//TY_INT_TOF_JITTER_THRESHOLD
DepthStreamTofJitterThreshold_RegAddr,integer,4
DepthStreamTofJitterThresholdMin_RegAddr,integer,4
DepthStreamTofJitterThresholdMax_RegAddr,integer,4

//TY_INT_X3MTOF_MOD
TofModParam_RegAddr,integer,4

//TY_BYTEARRAY_TOF_FMOD_PARAMETER
TofFmodParam0_RegAddr,integer,4
TofFmodParam1_RegAddr,integer,4

//TY_BYTEARRAY_TOF_LIGHT_DELAY_PARAMETER
TofLightDelayParam0_RegAddr,integer,4
TofLightDelayParam1_RegAddr,integer,4
TofLightDelayParam2_RegAddr,integer,4

//Tof Cali
TofCaliReserved,integer,256,0x900000
TofCaliPhaseShiftbit_RegAddr,integer,4
TofCaliXyzratioShiftbit_RegAddr,integer,4
TofCaliMaxdis2piShiftbit_RegAddr,integer,4
TofCaliFppnFixedIimeDelay_RegAddr,integer,4
TofCaliLaserType_RegAddr,integer,4
TofCaliFreWorkType_RegAddr,integer,4
TofCaliLumCutMax_RegAddr,integer,4
TofCaliLumCutMin_RegAddr,integer,4
TofCaliLumCutMod_RegAddr,integer,4
TofCaliCos2Shiftbit_RegAddr,integer,4
TofCaliLaser_RegAddr,integer,4

TofCaliCh0Freq1_RegAddr,integer,4,0x900400
TofCaliCh0UseFreq1_RegAddr,integer,4
TofCaliCh0Freq2_RegAddr,integer,4
TofCaliCh0UseFreq2_RegAddr,integer,4

TofCaliCh1Freq1_RegAddr,integer,4,0x900500
TofCaliCh1UseFreq1_RegAddr,integer,4
TofCaliCh1Freq2_RegAddr,integer,4
TofCaliCh1UseFreq2_RegAddr,integer,4

TofCaliCh2Freq1_RegAddr,integer,4,0x900600
TofCaliCh2UseFreq1_RegAddr,integer,4
TofCaliCh2Freq2_RegAddr,integer,4
TofCaliCh2UseFreq2_RegAddr,integer,4

TofCaliCh3Freq1_RegAddr,integer,4,0x900700
TofCaliCh3UseFreq1_RegAddr,integer,4
TofCaliCh3Freq2_RegAddr,integer,4
TofCaliCh3UseFreq2_RegAddr,integer,4

TofCaliCh4Freq1_RegAddr,integer,4,0x900800
TofCaliCh4UseFreq1_RegAddr,integer,4
TofCaliCh4Freq2_RegAddr,integer,4
TofCaliCh4UseFreq2_RegAddr,integer,4

DepthStreamTofHdrRatioInq_RegAddr,integer,4,0x900a00
)CSVDATA";

inline constexpr std::string_view kLightSourceCsv = R"CSVDATA(

//------------------------------LightSource Register---------------------------//
//------------------------------BASE ADDR: 0x07000000 -------------------------//
//Block0 : 0x300000 - 0x400000
//Block1 : 0x400000 - 0xFFFFFF
//----------------------------LightSource Register <Block0>-------------------//
//-------------------------------0x300000 - 0x400000---------------------------//
LightSourceEnableMask_RegAddr,integer,4,0x300000

//----------------------------LightSource Register <Block1>-------------------//
//-------------------------------0x400000 - 0xFFFFFF---------------------------//
//----------Light source component Function/Parameter Query register address---------//
LightSourceFuncInq_RegAddr,struct,4,0x400000,LightSourceCategory_RegAddr,RO,Light Source Func Inq
//LaserPower auto ctrl function
LaserPowerAutoCtrlSupportInq_Bit
//LaserPower Brightness control function
LaserPowerCtrlSupportInq_Bit
//IR light source control function
IRFlashLightSupportInq_Bit
//Color light source control function
ColorFlashLightSupportInq_Bit
//Light brightness ratio control function
LightBrightnessRatioSupportInq_Bit

//////////////////////////////////////////////////////////////////////////////////////////////////////
//The actual offset address corresponding to the current stream index, with multiple consecutive uint32_t values storing the offset addresses of different streams respectively.
//Laser_Power_En_RegAddr / IR_FlashLight_En_RegAddr / Color_FlashLight_En_RegAddr
CurrentLight_BaseRegAddr,integer,0

//%headercode
//Laser auto ctrl enable
Laser_Power_En_RegAddr,integer,4
//Laser brightness
Laser_Power_RegAddr,integer,4
//Laser brightness min
Laser_PowerMin_RegAddr,integer,4
//Laser brightness max
Laser_PowerMax_RegAddr,integer,4

//IR Flash light output enable
IR_FlashLight_En_RegAddr,integer,4
//IR Flash light brightness
IR_FlashLight_Power_RegAddr,integer,4
//IR Flash light brightness min
IR_FlashLight_PowerMin_RegAddr,integer,4
//IR Flash light brightness max
IR_FlashLight_PowerMax_RegAddr,integer,4

//Color Flash light output enable
Color_FlashLight_En_RegAddr,integer,4
//Color Flash light brightness
Color_FlashLight_Power_RegAddr,integer,4
//Color Flash light brightness min
Color_FlashLight_PowerMin_RegAddr,integer,4
//Color Flash light brightness max
Color_FlashLight_PowerMax_RegAddr,integer,4
//Light brightness ratio
LightBrightnessRatio_RegAddr,float,4,

LaserPatternIndex,integer,0,0
IRLightControllerIndex,integer,0,1
VisibleLightControllerIndex,integer,0,2


%xmlcode
<Enumeration Name="LightControllerSelector" NameSpace="Standard">
  <!-- Optional element -->
  <ToolTip>Selects the Light Controller to configure.</ToolTip>
  <Description>Selects the Light Controller to configure.</Description>
  <DisplayName>Light Controller Selector</DisplayName>
  <Visibility>Beginner</Visibility>
  <ImposedAccessMode>RW</ImposedAccessMode>
  <EnumEntry Name="LightController0" NameSpace="Standard">
    <ToolTip>Laser Pattern</ToolTip>
    <Description>Laser Pattern</Description>
    <DisplayName>Laser Pattern</DisplayName>
    <pIsImplemented>LaserPowerCtrlSupportInq_Bit</pIsImplemented>
    <Value>0</Value>
  </EnumEntry>
  <EnumEntry Name="LightController1" NameSpace="Standard">
    <ToolTip>IR Light Controller</ToolTip>
    <Description>IR Light Controller</Description>
    <DisplayName>IR Light Controller</DisplayName>
    <pIsImplemented>IRFlashLightSupportInq_Bit</pIsImplemented>
    <Value>1</Value>
  </EnumEntry>
  <EnumEntry Name="LightController2" NameSpace="Standard">
    <ToolTip>Visible Light Controller</ToolTip>
    <Description>Visible Light Controller</Description>
    <DisplayName>Visible Light Controller</DisplayName>
    <pIsImplemented>ColorFlashLightSupportInq_Bit</pIsImplemented>
    <Value>2</Value>
  </EnumEntry>
  <pValue>CurrentLight_BaseIdxReg</pValue>
  <pSelected>LightEnable</pSelected>
  <pSelected>LightBrightness</pSelected>
  <pSelected>LightBrightnessRatio</pSelected>
</Enumeration>
<Integer Name="CurrentLight_BaseIdxReg" NameSpace="Custom">
  <ImposedAccessMode>RW</ImposedAccessMode>
  <Value>0</Value>
</Integer>

<IntSwissKnife Name="CurrentLight_Offset">
  <Visibility>Invisible</Visibility>
  <pVariable Name="CATEGORY">LightSourceCategory_RegAddr</pVariable>
  <pVariable Name="BASE">CurrentLight_BaseRegAddr</pVariable>
  <pVariable Name="IDX">CurrentLight_BaseIdxReg</pVariable>
  <Formula>CATEGORY + BASE + IDX*16</Formula>
</IntSwissKnife>

<Integer Name="CurrentLightEnableAddress_Reg">
  <Value>0</Value>
</Integer>

<Integer Name="CurrentLightIntensityAddress_Reg">
  <Value>4</Value>
</Integer>

<Integer Name="CurrentLightIntensityMinAddress_Reg">
  <Value>8</Value>
</Integer>

<Integer Name="CurrentLightIntensityMaxAddress_Reg">
  <Value>12</Value>
</Integer>

<!--LightControl-->
<Boolean Name="LightEnable" NameSpace="Custom">
  <ToolTip>Light Source Enable.</ToolTip>
  <Description>Light Source Enable.</Description>
  <DisplayName>Light Source Enable</DisplayName>
  <Visibility>Beginner</Visibility>
  <!--<pIsAvailable>LaserPowerCtrl_Inq</pIsAvailable>-->
  <pIsAvailable>LightCtrl_Inq</pIsAvailable>
  <ImposedAccessMode>RW</ImposedAccessMode>
  <pValue>CurrentLightEnable_Reg</pValue>
</Boolean>

<!--
<IntSwissKnife Name="LaserPowerCtrl_Inq">
  <Visibility>Invisible</Visibility>
  <pVariable Name="CurrentLight">CurrentLight_BaseIdxReg</pVariable>
  <pVariable Name="DepthEn">DepthStreamEnable_Bit</pVariable>
  <Formula>!((CurrentLight == 0) &amp;&amp; DepthEn) </Formula>
</IntSwissKnife>
-->

<IntReg Name="CurrentLightEnable_Reg">
  <pAddress>CurrentLight_Offset</pAddress>
  <pAddress>CurrentLightEnableAddress_Reg</pAddress>
  <Length>4</Length>
  <AccessMode>RW</AccessMode>
  <pPort>Device</pPort>
  <pInvalidator>LightControllerSelector</pInvalidator>
  <pInvalidator>SourceSelector</pInvalidator>
  <pInvalidator>ComponentEnable</pInvalidator>
  <pInvalidator>UserSetLoad</pInvalidator>
  <Sign>Unsigned</Sign>
  <Endianess>LittleEndian</Endianess>
</IntReg>

<Integer Name="LightBrightness" NameSpace="Standard">
  <!-- Optional element -->
  <ToolTip>Set the brightness of the lighting output.</ToolTip>
  <Description>Set the brightness of the lighting output.</Description>
  <DisplayName>Light Brightness</DisplayName>
  <Visibility>Beginner</Visibility>
  <ImposedAccessMode>RW</ImposedAccessMode>
  <pValue>LightIntensity_Reg</pValue>
  <pMin>LightIntensityMin_Reg</pMin>
  <pMax>LightIntensityMax_Reg</pMax>
</Integer>

<IntReg Name="LightIntensity_Reg" NameSpace="Custom">
  <pAddress>CurrentLight_Offset</pAddress>
  <pAddress>CurrentLightIntensityAddress_Reg</pAddress>
  <Length>4</Length>
  <AccessMode>RW</AccessMode>
  <pPort>Device</pPort>   
  <pInvalidator>UserSetLoad</pInvalidator>
  <pInvalidator>LightControllerSelector</pInvalidator>
  <Sign>Unsigned</Sign>
  <Endianess>LittleEndian</Endianess>
</IntReg>

<IntReg Name="LightIntensityMin_Reg" NameSpace="Custom">
  <pAddress>CurrentLight_Offset</pAddress>
  <pAddress>CurrentLightIntensityMinAddress_Reg</pAddress>
  <Length>4</Length>
  <AccessMode>RO</AccessMode>
  <pPort>Device</pPort>   
  <pInvalidator>LightControllerSelector</pInvalidator>
  <Sign>Unsigned</Sign>
  <Endianess>LittleEndian</Endianess>
</IntReg>

<IntReg Name="LightIntensityMax_Reg" NameSpace="Custom">
  <pAddress>CurrentLight_Offset</pAddress>
  <pAddress>CurrentLightIntensityMaxAddress_Reg</pAddress>
  <Length>4</Length>
  <AccessMode>RO</AccessMode>
  <pPort>Device</pPort>   
  <pInvalidator>LightControllerSelector</pInvalidator>
  <Sign>Unsigned</Sign>
  <Endianess>LittleEndian</Endianess>
</IntReg>

%enddef)CSVDATA";

inline constexpr std::string_view kAdditionalCsv = R"CSVDATA(

//////////////////////////////////////////////////////////////////////////////////////////////////////
//-----------------------------UserSet Control Register----------------------------//
//------------------------------BASE ADDR: 0x0a000000 -----------------------------//
//--------------------------------0x400000 - 0xFFFFFF------------------------------//
//UserSet control  BaseAddressL:UserSetCategory_RegAddr
UserSetSelector_Inq_RegAddr,struct,4,0x400000,UserSetCategory_RegAddr,RO,User set selector Inq
invalidator,UserSetSelector
invalidator,UserSetSave
invalidator,UserSetDescription
UserSetSelector_Default0_Inq,bit,0
UserSetSelector_Default1_Inq
UserSetSelector_Default2_Inq
UserSetSelector_Default3_Inq
UserSetSelector_Default4_Inq
UserSetSelector_Default5_Inq
UserSetSelector_Default6_Inq
UserSetSelector_Default7_Inq
UserSetSelector_UserSet0_Inq
UserSetSelector_UserSet1_Inq
UserSetSelector_UserSet2_Inq
UserSetSelector_UserSet3_Inq
UserSetSelector_UserSet4_Inq
UserSetSelector_UserSet5_Inq
UserSetSelector_UserSet6_Inq
UserSetSelector_UserSet7_Inq
UserSetDescription_Inq,bit,30
UserSetLoad_Inq,bit,31

UserSetCurrent_RegAddr,integer,4
UserSetSelector_RegAddr,integer,4
UserSetDescription_RegAddr,string,512,0x0100
UserSetLoad_RegAddr,integer,4
UserSetSave_RegAddr,integer,4
UserSetDefaultSelector_RegAddr,integer,4

%xmlcode
<IntReg Name="SourceBaseAddress_Reg" NameSpace="Standard">
  <IntSwissKnife Name="SourceAddress_Int">
    <Visibility>Invisible</Visibility>
    <pVariable Name="BASE">CurrentSource_BaseRegAddr</pVariable>
    <pVariable Name="IDX">CurrentSource_BaseIdxReg</pVariable>
    <Formula>BASE + IDX*4</Formula>
  </IntSwissKnife>
  <Length>4</Length>
  <AccessMode>RO</AccessMode>
  <pPort>Device</pPort>
  <Sign>Unsigned</Sign>
  <Endianess>LittleEndian</Endianess>
</IntReg>

<IntReg Name="UserSetSelectorInq_Reg" NameSpace="Custom">
  <Visibility>Invisible</Visibility>
  <pAddress>UserSetCategory_RegAddr</pAddress>
  <Address>0x400000</Address>
  <Length>4</Length>
  <AccessMode>RO</AccessMode>
  <pPort>Device</pPort>
  <pInvalidator>UserSetSave</pInvalidator>
  <Sign>Unsigned</Sign>
  <Endianess>LittleEndian</Endianess>
</IntReg>

%enddef


//////////////////////////////////////////////////////////////////////////////////////////////////////
//-----------------------------FILE Access Control Register------------------------//
//------------------------------BASE ADDR: 0x0b000000 -----------------------------//
//--------------------------------0x400000 - 0xFFFFFF------------------------------//
CustomFileSelector_Inq_RegAddr,struct,4,0x400000,FileAccessCtrlCategory_RegAddr,RO,Custom File Selector Inquiry Register
CustomFileSelector_Default0_Inq,bit,0
CustomFileSelector_Default1_Inq
CustomFileSelector_Default2_Inq
CustomFileSelector_Default3_Inq
CustomFileSelector_Default4_Inq
CustomFileSelector_Default5_Inq
CustomFileSelector_Default6_Inq
CustomFileSelector_Default7_Inq

FileAccessControl_Inq_RegAddr,struct,4,,FileAccessCtrlCategory_RegAddr,RO,FileAccessControl Inquiry Register
FileOperationExecute_Inq,bit,0
FileAccessBuffer_Inq
FileAccessOffset_Inq
FileAccessLength_Inq
FileOperationStatus_Inq
FileOperationResult_Inq
FileSize_Inq

FileOperationSelector_Inq_RegAddr,struct,4,,FileAccessCtrlCategory_RegAddr,RO,File Operation Selector Inquiry Register
invalidator,FileSelector
invalidator,FileOpenMode
FileOperationOpen_Inq,bit,0
FileOperationClose_Inq
FileOperationRead_Inq
FileOperationWrite_Inq
FileOperationDelete_Inq

FileOperationSelector_AvaInq_RegAddr,struct,4,,FileAccessCtrlCategory_RegAddr,RO,File Operation Selector Available Inquiry Register
invalidator,FileSelector
invalidator,FileOpenMode
FileOperationSelector_Open_Inq,bit,0
FileOperationSelector_Close_Inq
FileOperationSelector_Read_Inq
FileOperationSelector_Write_Inq
FileOperationSelector_Delete_Inq

FileOpenMode_Inq_RegAddr,struct,4,,FileAccessCtrlCategory_RegAddr,RO,File Open Mode Inquiry Register
invalidator,FileSelector
FileOpenModeRO_Inq,bit,0
FileOpenModeWO_Inq
FileOpenModeRW_Inq

FileOpenMode_AvaInq_RegAddr,struct,4,,FileAccessCtrlCategory_RegAddr,RO,File Open Mode Available Inquiry Register
invalidator,FileSelector
FileOpenMode_RO_InqAvailable,bit,0
FileOpenMode_WO_InqAvailable
FileOpenMode_RW_InqAvailable

FileSelector_RegAddr,integer,4
FileOperationSelector_RegAddr,integer,4
FileOperationExecute_RegAddr,integer,4
FileOpenMode_RegAddr,integer,4
FileAccessBuffer_RegAddr,integer,4

FileAccessOffsetMinInq_RegAddr,integer,4
FileAccessOffsetMaxInq_RegAddr,integer,4
FileAccessOffsetIncInq_RegAddr,integer,4
FileAccessOffset_RegAddr,integer,4

FileAccessLengthMinInq_RegAddr,integer,4
FileAccessLengthMaxInq_RegAddr,integer,4
FileAccessLengthIncInq_RegAddr,integer,4
FileAccessLength_RegAddr,integer,4

FileOperationStatus_RegAddr,integer,4
FileOperationResult_RegAddr,integer,4

FileSize_RegAddr,integer,4


//////////////////////////////////////////////////////////////////////////////////////////////////////
//-----------------------------Sequencer Control Register--------------------------//
//------------------------------BASE ADDR: 0x0c000000 -----------------------------//
//--------------------------------0x400000 - 0xFFFFFF------------------------------//
//SequencerTriggerSource Inq Register
SeqTriggerSource_Inq_RegAddr,struct,4,0x400000,SequencerCtrlCategory_RegAddr,RO,Sequencer Control Trigger Source Inquiry Register
SeqTriggerSource_Line0_Inq_Bit,bit,0
SeqTriggerSource_Line1_Inq_Bit
SeqTriggerSource_Line2_Inq_Bit
SeqTriggerSource_Line3_Inq_Bit
SeqTriggerSource_Line4_Inq_Bit
SeqTriggerSource_Line5_Inq_Bit
SeqTriggerSource_Line6_Inq_Bit
SeqTriggerSource_Line7_Inq_Bit
SeqTriggerSource_Sw_Inq_Bit
SeqTriggerSource_AcqStart_Inq_Bit
SeqTriggerSource_AcqEnd_Inq_Bit
SeqTriggerSource_FrameStart_Inq_Bit
SeqTriggerSource_FrameEnd_Inq_Bit
SeqTriggerSource_FrameBStart_Inq_Bit
SeqTriggerSource_FrameBEnd_Inq_Bit
SeqTriggerSource_ExpStart_Inq_Bit
SeqTriggerSource_ExpEnd_Inq_Bit

//SequencerTriggerActivation Inq Register
SeqTriggerActivation_Inq_RegAddr,struct,4,,SequencerCtrlCategory_RegAddr,RO,Sequencer Control Trigger Activation Inquiry Register
SeqTriggerActivation_RisingEdge_Inq_Bit,bit,0
SeqTriggerActivation_FallingEdge_Inq_Bit
SeqTriggerActivation_AnyEdge_Inq_Bit
SeqTriggerActivation_LevelHigh_Inq_Bit
SeqTriggerActivation_LevelLow_Inq_Bit
SeqTriggerActivation_None_Inq_Bit,bit,31

//SequencerMode,Enumeration
SequencerMode_RegAddr,integer,4

//SequencerConfigurationMode,Enumeration
SequencerConfigurationMode_RegAddr,integer,4

//SequencerSetSelector,Integer
SequencerSetSelector_RegAddr,integer,4
SequencerSetSelectorMax_RegAddr,integer,4
SequencerSetSelectorMin_RegAddr,integer,4

//SequencerSetReset,Command
SequencerSetReset_RegAddr,integer,4

//SequencerSetSave,Command
SequencerSetSave_RegAddr,integer,4

//SequencerSetLoad,Command
SequencerSetLoad_RegAddr,integer,4

//SequencerSetActive,Integer
SequencerSetActive_RegAddr,integer,4

//SequencerSetStart,Integer
SequencerSetStart_RegAddr,integer,4

//SequencerPathSelector,Integer
SequencerPathSelector_RegAddr,integer,4
SequencerPathSelectorMax_RegAddr,integer,4
SequencerPathSelectorMin_RegAddr,integer,4

//SequencerSetNext,Integer
SequencerSetNext_RegAddr,integer,4

//SequencerTriggerSource,Enumeration
SequencerTriggerSource_RegAddr,integer,4

//SequencerTriggerActivation,Enumeration
SequencerTriggerActivation_RegAddr,integer,4
)CSVDATA";

inline constexpr std::string_view kEventCsv = R"CSVDATA(
PrimaryApplicationSwitch_EventId,EventId,0x0007
LinkSpeedChange_EventId,EventId,0x0008
Test_EventId,EventId,0x4fff
FrameTrigger_EventId,EventId,0x9000
FrameTriggerMissed_EventId,EventId,0x9001
Error_EventId,EventId,0x9002
IMU_EventId,EventId,0x9003

%event_xmlcode
<Group Comment="EventControl">
  <Enumeration Name="EventSelector" NameSpace="Standard">
    <ToolTip>Selects which Event to signal to the host application.</ToolTip>
    <Description>Selects which Event to signal to the host application.</Description>
    <DisplayName>Event Selector</DisplayName>
    <Visibility>Expert</Visibility>
    <pIsImplemented>EventControl_SupportInq_Bit</pIsImplemented>
    <ImposedAccessMode>RW</ImposedAccessMode>
    <EnumEntry Name="PrimaryApplicationSwitch" NameSpace="Standard">
      <ToolTip>The event will be generated when a primary application switchover has been granted (GigE Vision Specific).</ToolTip>
      <Description>The event will be generated when a primary application switchover has been granted (GigE Vision Specific).</Description>
      <DisplayName>Primary Application Switch</DisplayName>
      <pIsImplemented>EventControl_PrimaryApplicationSwitch_Inq_Bit</pIsImplemented>
      <Value>%PrimaryApplicationSwitch_EventId%</Value>
    </EnumEntry>
    <EnumEntry Name="LinkSpeedChange" NameSpace="Standard">
      <ToolTip>The event will be generated when the link speed has changed.</ToolTip>
      <Description>The event will be generated when the link speed has changed.</Description>
      <DisplayName>Link Speed Change</DisplayName>
      <pIsImplemented>EventControl_LinkSpeedChange_Inq_Bit</pIsImplemented>
      <Value>%LinkSpeedChange_EventId%</Value>
    </EnumEntry>
    <EnumEntry Name="Test" NameSpace="Standard">
      <ToolTip>The test event will be generated when the device receives the TestEventGenerate command (EventNotification for the Test event is always On).</ToolTip>
      <Description>The test event will be generated when the device receives the TestEventGenerate command (EventNotification for the Test event is always On).</Description>
      <DisplayName>Test</DisplayName>
      <pIsImplemented>EventControl_Test_Inq_Bit</pIsImplemented>
      <Value>%Test_EventId%</Value>
    </EnumEntry>
    <EnumEntry Name="FrameTrigger" NameSpace="Standard">
      <ToolTip>Device just received a trigger to start the capture of one Frame.</ToolTip>
      <Description>Device just received a trigger to start the capture of one Frame.</Description>
      <DisplayName>Frame Trigger</DisplayName>
      <pIsImplemented>EventControl_FrameTrigger_Inq_Bit</pIsImplemented>
      <Value>%FrameTrigger_EventId%</Value>
    </EnumEntry>
    <EnumEntry Name="FrameTriggerMissed" NameSpace="Standard">
      <ToolTip>Device just missed a trigger to start the capture of one Frame.</ToolTip>
      <Description>Device just missed a trigger to start the capture of one Frame.</Description>
      <DisplayName>Frame Trigger Missed</DisplayName>
      <pIsImplemented>EventControl_FrameTriggerMissed_Inq_Bit</pIsImplemented>
      <Value>%FrameTriggerMissed_EventId%</Value>
    </EnumEntry>
    <EnumEntry Name="Error" NameSpace="Standard">
      <ToolTip>Device just detected an error during the active Acquisition.</ToolTip>
      <Description>Device just detected an error during the active Acquisition.</Description>
      <DisplayName>Error</DisplayName>
      <pIsImplemented>EventControl_Error_Inq_Bit</pIsImplemented>
      <Value>%Error_EventId%</Value>
    </EnumEntry>
    <EnumEntry Name="IMU" NameSpace="Standard">
      <ToolTip>IMU sensor data event. It contains accelerometer and gyroscope samples from the device's IMU sensor.</ToolTip>
      <Description>IMU sensor data event. It contains accelerometer and gyroscope samples from the device's IMU sensor.</Description>
      <DisplayName>IMU</DisplayName>
      <pIsImplemented>EventControl_IMU_Inq_Bit</pIsImplemented>
      <Value>%IMU_EventId%</Value>
    </EnumEntry>
    <pValue>EventSelector_Reg</pValue>
  </Enumeration>
  <IntReg Name="EventSelector_Reg" NameSpace="Custom">
    <Visibility>Invisible</Visibility>
    <pAddress>DeviceCategory_RegAddr</pAddress>
    <pAddress>EventSelector_RegAddr</pAddress>
    <Length>4</Length>
    <AccessMode>RW</AccessMode>
    <pPort>Device</pPort>
    <Endianess>LittleEndian</Endianess>
  </IntReg>
</Group>

<Port Name="EventLinkSpeedChangePort" NameSpace="Custom">
    <EventID>%PrimaryApplicationSwitch_EventId%</EventID>
    <pIsImplemented>EventControl_SupportInq_Bit</pIsImplemented>
</Port>
<Port Name="EventTestPort" NameSpace="Custom">
    <EventID>%Test_EventId%</EventID>
    <pIsImplemented>EventControl_SupportInq_Bit</pIsImplemented>
</Port>
<Port Name="EventFrameTriggerPort" NameSpace="Custom">
    <EventID>%FrameTrigger_EventId%</EventID>
    <pIsImplemented>EventControl_SupportInq_Bit</pIsImplemented>
</Port>
<Port Name="EventFrameTriggerMissedPort" NameSpace="Custom">
    <EventID>%FrameTriggerMissed_EventId%</EventID>
    <pIsImplemented>EventControl_SupportInq_Bit</pIsImplemented>
</Port>
<Port Name="EventErrorPort" NameSpace="Custom">
    <EventID>%Error_EventId%</EventID>
    <pIsImplemented>EventControl_SupportInq_Bit</pIsImplemented>
</Port>
<Port Name="EventIMUPort" NameSpace="Custom">
    <EventID>%IMU_EventId%</EventID>
    <pIsImplemented>EventControl_SupportInq_Bit</pIsImplemented>
</Port>

%enddef
)CSVDATA";

struct CsvFile {
    std::string_view path;
    std::string_view content;
};

inline constexpr CsvFile kFiles[9] = {
    {"GigE/BootstrapReg.csv", kGigEBootstrapRegCsv},
    {"gmsl/BootstrapReg.csv", kGmslBootstrapRegCsv},
    {"usb3vison/BootstrapReg.csv", kUsb3visonBootstrapRegCsv},
    {"BaseReg.csv", kBaseRegCsv},
    {"Device.csv", kDeviceCsv},
    {"Stream.csv", kStreamCsv},
    {"LightSource.csv", kLightSourceCsv},
    {"Additional.csv", kAdditionalCsv},
    {"Event.csv", kEventCsv},
};

} // namespace regaddr_csv_data

#endif // REGADDR_CSV_DATA_H
